import {InfotecFooter} from "../components/InfotecFooter";

const modules=[
 ["01 · COMMAND CENTER","Central de decisão","Uma fila única com incidentes, oportunidades, aprovações, tracking, tarefas e saúde da carteira."],
 ["02 · PERFORMANCE INTELLIGENCE","Profit ROAS","Cruza receita real, mídia, fee, despesas e custo de horas para estimar retorno operacional além do ROAS da plataforma."],
 ["03 · TRACKING GUARDIAN","Tracking 24/7","Consolida checks de mensuração e saúde das integrações para encontrar falhas antes de escalar investimento."],
 ["04 · LEAD QUALITY","Qualidade até a venda","Confronte CPL com lead qualificado, oportunidade, venda e CAC quando o CRM estiver conectado."],
 ["05 · BUDGET OPTIMIZER","Cenários de verba","Simule como redistribuir orçamento usando eficiência observada, projeções e guardrails sem alterar campanhas automaticamente."],
 ["06 · FORECAST","Metas e projeções","Acompanhe projeções de leads e receita e a probabilidade de atingir metas a partir dos dados disponíveis."],
 ["07 · CREATIVE INTELLIGENCE","Creative DNA + fadiga","Cruze fadiga, hook, CPA, CTR e histórico e registre DNA criativo por formato, ângulo, CTA e oferta."],
 ["08 · CLIENT HEALTH","Health + churn","Marketing, tracking, criativo, relacionamento e financeiro viram um Health Score com risco operacional de churn."],
 ["09 · EXPERIMENT ENGINE","Testes A/B","Detecte experimentos, registre hipóteses e transforme resultados em aprendizado reutilizável."],
 ["10 · ATTRIBUTION","Verdade do negócio","Compare receita atribuída pelos anúncios com vendas, CRM, e-commerce e resultados realmente confirmados."],
 ["11 · CLIENT SUCCESS","Portal e aprovações","Relatórios, portal do cliente, chamados, projetos e aprovações externas com histórico."],
 ["12 · OPERATIONS 360","Operação da agência","Projetos, horas, capacidade, despesas, processos, conteúdo, ativos, conhecimento, roadmap e suporte."]
];
const integrations=[["M","Meta Ads"],["G","Google Ads"],["TT","TikTok Ads"],["in","LinkedIn Ads"],["MS","Microsoft Ads"],["GA","Google Analytics 4"],["SC","Search Console"],["H","HubSpot"],["RD","RD Station"],["S","Shopify"],["API","CRM / Webhook"],["+","Novas fontes"]];
const intelligence=[
 ["Profit ROAS","Saiba quanto sobra depois de mídia e custos operacionais disponíveis — não apenas o retorno reportado pela plataforma."],
 ["Tracking Guardian","Encontre checks e integrações com falha antes de tomar uma decisão de escala."],
 ["Lead Quality","Veja CPL, CPL qualificado e CAC quando o funil real estiver conectado."],
 ["Budget Optimizer","Crie cenários de distribuição de verba e salve a recomendação antes de qualquer execução."],
 ["Client Health 360","Compare saúde de marketing, tracking, criativos, relacionamento e financeiro por cliente."],
 ["Churn Predictor","Priorize clientes com maior risco operacional e abra um plano de retenção antes da crise."],
 ["Creative Intelligence","Use fadiga, hook e performance para aprender quais padrões criativos merecem novas variações."],
 ["TrafiNexo Copilot","Pergunte à operação sobre risco, tracking, verba, Profit ROAS, leads e criativos com resposta baseada em evidências."]
];
export default function Home(){return <main className="public-shell"><header className="public-header"><div className="container header-inner"><a className="brand" href="/"><span className="brand-mark">T</span><div><strong>TRAFINEXO</strong><small>by INFOTEC</small></div></a><nav><a href="#produto">Produto</a><a href="#inteligencia">Inteligência</a><a href="#integracoes">Integrações</a><a className="nav-login" href="/login">Entrar</a><a className="btn" href="/cadastro">Testar 15 dias</a></nav></div></header>
<section className="hero-pro"><div className="container hero-pro-grid"><div><span className="eyebrow">PERFORMANCE INTELLIGENCE PARA GESTORES E AGÊNCIAS</span><h1>Descubra onde o dinheiro está sendo perdido.<br/><span>E qual é a próxima melhor ação.</span></h1><p className="lead">O Trafinexo conecta mídia, operação e resultado real para mostrar Profit ROAS, qualidade dos leads, falhas de tracking, risco de churn, fadiga criativa e cenários de orçamento em uma única central de decisão.</p><div className="hero-actions"><a className="btn" href="/cadastro">Começar 15 dias grátis →</a><a className="btn ghost" href="#inteligencia">Ver inteligência de performance</a></div><div className="hero-note"><span>✓ Sem cartão no teste</span><span>✓ Todas as funções</span><span>✓ Depois R$ 29,90/mês</span><span>✓ Android/PWA</span></div></div><div className="command-preview"><div className="preview-window"><div className="preview-bar"><i/><i/><i/></div><div className="preview-body"><aside className="preview-side"><b>T</b><span>⌁</span><span>◎</span><span>↗</span><span>AI</span><span>!</span></aside><section className="preview-main"><div className="preview-head"><div><small>TRAFINEXO / INTELIGÊNCIA</small><strong>Bom dia. Aqui está o que exige atenção.</strong></div><span className="live-dot">● dados sincronizados</span></div><div className="preview-kpis"><div><small>ROAS negócio</small><b>3,62x</b></div><div><small>Profit ROAS</small><b>2,14x</b></div><div><small>Health médio</small><b>82/100</b></div></div><div className="decision-card"><small>FILA DE DECISÃO</small><div className="decision-item"><i/><div><b>Tracking exige atenção</b><span>evento de conversão inconsistente · Cliente A</span></div><em>Investigar →</em></div><div className="decision-item"><i/><div><b>Cliente com risco de churn</b><span>resultado + chamados + tarefas em atraso</span></div><em>Plano de ação →</em></div><div className="decision-item ok"><i/><div><b>Oportunidade de escala</b><span>Profit ROAS saudável + tracking estável</span></div><em>Simular verba →</em></div></div></section></div></div></div></div></section>
<section className="proof-strip"><div className="container proof-grid"><div><b>Profit ROAS</b><span>resultado além do dashboard de anúncios</span></div><div><b>Lead → venda</b><span>qualidade do funil quando CRM estiver conectado</span></div><div><b>Tracking Guardian</b><span>mensuração antes de escala</span></div><div><b>Aprovação humana</b><span>guardrail para ações que mexem em verba</span></div></div></section>
<section className="section" id="produto"><div className="container"><div className="section-head center"><small>POR QUE O TRAFINEXO EXISTE</small><h2>Dashboard mostra métrica. O Trafinexo organiza a decisão.</h2><p>Gestores e agências precisam descobrir rapidamente onde há perda, qual cliente corre risco, que criativo está cansando, se o tracking é confiável e onde a próxima verba tem maior chance de retornar.</p></div><div className="pain-grid"><article className="pain-card"><span>01</span><h3>ROAS sem lucro</h3><p>A plataforma pode mostrar retorno enquanto fee, mídia, horas, despesas e venda real contam outra história.</p></article><article className="pain-card"><span>02</span><h3>Lead barato e ruim</h3><p>CPL isolado não mostra qualidade. O Trafinexo está preparado para acompanhar o lead até oportunidade e venda.</p></article><article className="pain-card"><span>03</span><h3>Problema descoberto tarde</h3><p>Tracking, churn e fadiga criativa viram sinais de atenção para agir antes que o problema apareça no relatório do cliente.</p></article></div></div></section>
<section className="section solution-dark" id="inteligencia"><div className="container"><div className="section-head"><small>PERFORMANCE INTELLIGENCE</small><h2>Uma camada de inteligência sobre toda a operação.</h2><p>Os cálculos são explicáveis e mostram as evidências disponíveis. Quando faltam dados reais de CRM, margem ou integração, o sistema sinaliza a limitação em vez de inventar precisão.</p></div><div className="module-grid">{intelligence.map((m,i)=><article className="module-card" key={m[0]}><span>{String(i+1).padStart(2,"0")}</span><h3>{m[0]}</h3><p>{m[1]}</p></article>)}</div></div></section>
<section className="section" id="metodo"><div className="container"><div className="section-head"><small>FLUXO OPERACIONAL</small><h2>Conectar → validar → detectar → simular → aprovar → aprender.</h2><p>Automatize coleta e análise, mas mantenha aprovação humana nas ações de mídia que podem gastar dinheiro ou alterar entrega.</p></div><div className="workflow-row"><article><small>01</small><b>Conectar</b><p>Mídia, analytics, CRM e e-commerce entram no Data Hub.</p></article><article><small>02</small><b>Validar</b><p>Tracking Guardian verifica se os sinais usados na decisão estão saudáveis.</p></article><article><small>03</small><b>Detectar</b><p>Incidentes, churn, fadiga e perda de eficiência entram na fila.</p></article><article><small>04</small><b>Simular</b><p>Budget Optimizer e Forecast ajudam a comparar cenários antes da execução.</p></article><article><small>05</small><b>Aprender</b><p>Resultados, mudanças e Creative DNA alimentam a próxima decisão.</p></article></div></div></section>
<section className="section"><div className="container"><div className="section-head"><small>PLATAFORMA COMPLETA</small><h2>Da mídia à operação da agência.</h2><p>O Trafinexo combina performance, clientes, projetos, aprovações, atendimento, conhecimento e inteligência em um mesmo fluxo.</p></div><div className="module-grid">{modules.map(m=><article className="module-card" key={m[1]}><span>{m[0]}</span><h3>{m[1]}</h3><p>{m[2]}</p></article>)}</div></div></section>
<section className="section integration-section" id="integracoes"><div className="container"><div className="section-head"><small>DATA HUB</small><h2>Um lugar para mídia, analytics, CRM e e-commerce.</h2><p>O Trafinexo possui contratos de integração e diagnóstico seguro para as principais fontes. A disponibilidade E2E de cada provedor depende das credenciais, permissões e aprovações exigidas pela própria plataforma.</p></div><div className="integration-grid">{integrations.map(i=><article className="integration-card" key={i[1]}><span>{i[0]}</span><div><b>{i[1]}</b><small>Conectar, diagnosticar e centralizar dados</small></div></article>)}</div></div></section>
<section className="section"><div className="container truth-grid"><article className="truth-card"><small>PROFIT ROAS</small><h3>ROAS de plataforma não é automaticamente lucro.</h3><p>Além da receita atribuída, o motor considera mídia e custos operacionais disponíveis para estimar quanto resultado permanece depois do investimento.</p><div className="truth-list"><div><i/>ROAS plataforma x ROAS negócio</div><div><i/>Mídia + fee + despesas + custo de horas disponível</div><div><i/>Lucro operacional estimado com metodologia visível</div></div></article><article className="truth-card dark"><small>DECISION COPILOT</small><h3>Pergunte à sua operação.</h3><p>“Qual cliente está em risco?”, “tem falha de tracking?”, “onde devo colocar verba?” ou “como está a qualidade dos leads?”. O Copilot responde com base nas evidências que o Trafinexo possui.</p><div className="truth-list"><div><i/>Resposta analítica explicável</div><div><i/>Evidências auditáveis</div><div><i/>Sem executar alteração de mídia silenciosamente</div></div></article></div></section>
<section className="section pricing"><div className="container"><div className="price-card"><div><small>LANÇAMENTO INFOTEC</small><h2>15 dias para enxergar sua operação de outro jeito.</h2><p>Teste a central de performance, operação, portal, inteligência e integrações em um único plano. Recursos que dependem de APIs externas ficam sujeitos às permissões de cada provedor.</p><a className="btn" href="/cadastro">Começar gratuitamente</a></div><div className="price-value"><b>R$ 29,90</b><span>por mês após os 15 dias grátis</span></div></div></div></section><InfotecFooter/></main>}
