import {InfotecFooter} from "../components/InfotecFooter";

const modules=[
 ["01 · COMMAND CENTER","Central de comando","Uma fila única com alertas, integrações com erro, tarefas vencidas, oportunidades e saúde da carteira."],
 ["02 · MEDIA HUB","Mídia conectada","Meta Ads, Google Ads, TikTok Ads e outras fontes entram por OAuth/API e alimentam campanhas e métricas."],
 ["03 · EXPERIMENT ENGINE","Testes A/B","Detecta experimentos existentes, monitora variantes e permite criar hipóteses acompanhadas pelo Trafinexo."],
 ["04 · CREATIVE INTELLIGENCE","Criativos e fadiga","Biblioteca + performance. Fadiga só é sinalizada quando frequência, CTR, CPA e conversão convergem."],
 ["05 · ATTRIBUTION","Verdade do negócio","Compare receita atribuída pelos anúncios com vendas, CRM, e-commerce e resultados realmente confirmados."],
 ["06 · CLIENT SUCCESS","Relatórios e portal","Relatórios programados, resumo por IA, aprovação antes do envio, white-label e portal do cliente."],
 ["07 · ACTION CENTER","Alertas e recomendações","Transforme sinais em decisões priorizadas. Mudanças que gastam dinheiro continuam exigindo aprovação."],
 ["08 · OPERATIONS","Gestão da operação","Clientes, metas, tarefas, contratos, renovações, fees, verba e sugestões em uma única plataforma."]
];
const integrations=[["M","Meta Ads"],["G","Google Ads"],["TT","TikTok Ads"],["in","LinkedIn Ads"],["MS","Microsoft Ads"],["GA","Google Analytics 4"],["SC","Search Console"],["H","HubSpot"],["RD","RD Station"],["S","Shopify"],["API","CRM / Webhook"],["+","Novas fontes"]];
export default function Home(){return <main className="public-shell"><header className="public-header"><div className="container header-inner"><a className="brand" href="/"><span className="brand-mark">T</span><div><strong>TRAFINEXO</strong><small>by INFOTEC</small></div></a><nav><a href="#produto">Produto</a><a href="#integracoes">Integrações</a><a href="#metodo">Como funciona</a><a className="nav-login" href="/login">Entrar</a><a className="btn" href="/cadastro">Testar 15 dias</a></nav></div></header>
<section className="hero-pro"><div className="container hero-pro-grid"><div><span className="eyebrow">O SISTEMA OPERACIONAL DA SUA OPERAÇÃO DE TRÁFEGO</span><h1>Pare de alternar abas.<br/><span>Comece a decidir.</span></h1><p className="lead">Conecte contas de mídia, analytics e CRM. O Trafinexo sincroniza campanhas, monitora testes, encontra sinais de atenção e confronta o ROAS da plataforma com o que realmente virou negócio.</p><div className="hero-actions"><a className="btn" href="/cadastro">Começar 15 dias grátis →</a><a className="btn ghost" href="#produto">Conhecer a plataforma</a></div><div className="hero-note"><span>✓ Sem cartão no teste</span><span>✓ Todas as funções</span><span>✓ Depois R$ 29,90/mês</span><span>✓ Android/PWA</span></div></div><div className="command-preview"><div className="preview-window"><div className="preview-bar"><i/><i/><i/></div><div className="preview-body"><aside className="preview-side"><b>T</b><span>⌁</span><span>◎</span><span>↗</span><span>A/B</span><span>!</span></aside><section className="preview-main"><div className="preview-head"><div><small>TRAFINEXO / COMANDO</small><strong>Bom dia. Aqui está o que exige atenção.</strong></div><span className="live-dot">● dados sincronizados</span></div><div className="preview-kpis"><div><small>Investimento</small><b>R$ 48,2k</b></div><div><small>ROAS plataforma</small><b>4,18x</b></div><div><small>ROAS negócio</small><b>3,62x</b></div></div><div className="decision-card"><small>FILA DE DECISÃO</small><div className="decision-item"><i/><div><b>Criativo com possível fadiga</b><span>3 sinais convergentes · Cliente A</span></div><em>Revisar →</em></div><div className="decision-item"><i/><div><b>Campanha consumindo verba sem lead</b><span>tracking ou oferta podem precisar de atenção</span></div><em>Investigar →</em></div><div className="decision-item ok"><i/><div><b>Teste A/B com sinal forte</b><span>Variante B · 94,2% de confiança</span></div><em>Avaliar →</em></div></div></section></div></div></div></div></section>
<section className="proof-strip"><div className="container proof-grid"><div><b>1 clique</b><span>para conectar contas quando OAuth estiver disponível</span></div><div><b>1 hora</b><span>cadência padrão de sincronização automática</span></div><div><b>2 fontes</b><span>plataforma + negócio para validar atribuição</span></div><div><b>1 plano</b><span>todas as funções por R$ 29,90/mês após o trial</span></div></div></section>
<section className="section" id="produto"><div className="container"><div className="section-head center"><small>POR QUE O TRAFINEXO EXISTE</small><h2>Gestor de tráfego não precisa de mais um dashboard.</h2><p>Precisa reduzir trabalho repetitivo, encontrar problemas antes do cliente, provar impacto real e transformar dados em uma próxima ação clara.</p></div><div className="pain-grid"><article className="pain-card"><span>01</span><h3>Dados espalhados</h3><p>Meta, Google, TikTok, GA4, planilhas e CRM contam histórias diferentes. O Trafinexo centraliza a leitura.</p></article><article className="pain-card"><span>02</span><h3>Checagem manual</h3><p>Entrar conta por conta consome o tempo que deveria ir para estratégia, criativo e otimização.</p></article><article className="pain-card"><span>03</span><h3>Relatório sem decisão</h3><p>Mostrar métricas não explica o que aconteceu, por que importa e o que será feito em seguida.</p></article></div></div></section>
<section className="section solution-dark" id="metodo"><div className="container"><div className="section-head"><small>FLUXO OPERACIONAL</small><h2>Conectar → observar → decidir → testar → aprender.</h2><p>O Trafinexo foi desenhado ao redor do ciclo real de um gestor, com automação na coleta e aprovação humana nas ações de risco.</p></div><div className="workflow-row"><article><small>01</small><b>Conectar</b><p>Autorize mídia, analytics, CRM ou e-commerce.</p></article><article><small>02</small><b>Sincronizar</b><p>Campanhas, métricas e testes entram automaticamente.</p></article><article><small>03</small><b>Detectar</b><p>Anomalias, oportunidades e gaps viram fila de decisão.</p></article><article><small>04</small><b>Experimentar</b><p>Monitore testes existentes ou crie uma nova hipótese.</p></article><article><small>05</small><b>Aprender</b><p>Relatórios, recomendações e histórico melhoram a próxima decisão.</p></article></div></div></section>
<section className="section"><div className="container"><div className="section-head"><small>PLATAFORMA COMPLETA</small><h2>Um produto para operar a carteira inteira.</h2><p>As áreas foram reorganizadas para deixar as ações importantes explícitas e reduzir a sensação de ferramenta “cheia de telas”.</p></div><div className="module-grid">{modules.map(m=><article className="module-card" key={m[1]}><span>{m[0]}</span><h3>{m[1]}</h3><p>{m[2]}</p></article>)}</div></div></section>
<section className="section integration-section" id="integracoes"><div className="container"><div className="section-head"><small>DATA HUB</small><h2>As principais ferramentas do gestor já têm lugar definido.</h2><p>OAuth é o caminho preferido; quando a plataforma usa chave/token, a credencial é enviada ao backend e armazenada no Vault, sem ficar visível no navegador.</p></div><div className="integration-grid">{integrations.map(i=><article className="integration-card" key={i[1]}><span>{i[0]}</span><div><b>{i[1]}</b><small>Conectar e centralizar dados</small></div></article>)}</div></div></section>
<section className="section"><div className="container truth-grid"><article className="truth-card"><small>ATTRIBUTION</small><h3>ROAS do anúncio não é automaticamente lucro.</h3><p>O Trafinexo mantém a métrica da plataforma, mas também recebe vendas, oportunidades, reembolsos e receita real para mostrar o gap de atribuição.</p><div className="truth-list"><div><i/>Mídia e conversões da plataforma</div><div><i/>CRM / e-commerce / vendas confirmadas</div><div><i/>UTMs, click IDs e eventos offline</div></div></article><article className="truth-card dark"><small>CREATIVE INTELLIGENCE</small><h3>Fadiga criativa com contexto.</h3><p>Uma queda isolada não condena um anúncio. O motor só sinaliza fadiga quando múltiplos sinais convergem, reduzindo falsos alarmes.</p><div className="truth-list"><div><i/>Frequência e saturação</div><div><i/>CTR e entrega</div><div><i/>CPA, conversão e histórico</div></div></article></div></section>
<section className="section pricing"><div className="container"><div className="price-card"><div><small>LANÇAMENTO INFOTEC</small><h2>15 dias para conectar sua operação.</h2><p>Depois do teste, todas as funções continuam no mesmo plano. Sem liberar integrações, testes ou relatórios apenas em plano “premium”.</p><a className="btn" href="/cadastro">Começar gratuitamente</a></div><div className="price-value"><b>R$ 29,90</b><span>por mês após os 15 dias grátis</span></div></div></div></section><InfotecFooter/></main>}
