"use client";
import {useMemo} from "react";
import PortfolioCockpit from "./PortfolioCockpit";
import ProductGuide from "./ProductGuide";

const brl=v=>(Number(v||0)/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function CommandCenter({clients,campaigns,integrations,alerts,recommendations,tasks,outcomes,onNavigate}){
 const summary=useMemo(()=>{const spend=campaigns.reduce((a,c)=>a+Number(c.spend_cents||0),0),platformRevenue=campaigns.reduce((a,c)=>a+Number(c.revenue_cents||0),0),businessRevenue=outcomes.filter(o=>["sale","subscription"].includes(o.event_type)).reduce((a,o)=>a+Number(o.value_cents||0),0),leads=campaigns.reduce((a,c)=>a+Number(c.leads||0),0),conv=campaigns.reduce((a,c)=>a+Number(c.conversions||0),0);return{spend,platformRevenue,businessRevenue,leads,conv,roas:spend?platformRevenue/spend:0,trueRoas:spend?businessRevenue/spend:0,cpl:leads?spend/leads:0}},[campaigns,outcomes]);
 const overdue=tasks.filter(t=>t.status!=="done"&&t.due_at&&new Date(t.due_at)<new Date());
 const connectionErrors=integrations.filter(i=>i.connection_health==="error");
 const openAlerts=alerts.filter(a=>a.status==="open");
 const priorities=[...openAlerts.map(a=>({kind:"alert",level:a.severity,title:a.title,text:a.recommended_action||a.description,tab:"Mídia"})),...connectionErrors.map(i=>({kind:"integration",level:"high",title:`Integração ${i.provider} requer atenção`,text:i.last_error||"Reconecte ou sincronize a fonte de dados.",tab:"Integrações"})),...overdue.map(t=>({kind:"task",level:"medium",title:`Tarefa vencida: ${t.title}`,text:t.description||"Repriorize a tarefa ou conclua a ação.",tab:"Tarefas"})),...recommendations.filter(r=>r.status==="suggested").map(r=>({kind:"recommendation",level:r.priority==="urgent"?"critical":r.priority,title:r.title,text:r.rationale,tab:"Central de ação"}))].slice(0,8);
 const authorized=integrations.filter(i=>i.status==="authorized");
 const fresh=authorized.filter(i=>i.last_sync_at&&Date.now()-new Date(i.last_sync_at)<2*3600000).length;
 return <div className="ops-stack">
  <div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><div><span className="ops-eyebrow" style={{color:"#52708d",marginBottom:3}}>VISÃO DO GESTOR</span><b style={{fontSize:13}}>Carteira, performance e prioridades em uma única tela.</b></div><ProductGuide/></div>
  <div className="metric-ribbon"><Metric label="Investimento" value={brl(summary.spend)} note={`${campaigns.length} campanhas`}/><Metric label="Leads" value={summary.leads.toLocaleString("pt-BR")} note={`CPL ${brl(summary.cpl)}`}/><Metric label="Conversões" value={summary.conv.toLocaleString("pt-BR")} note={`${clients.length} clientes`}/><Metric label="CPL médio" value={summary.leads?brl(summary.cpl):"—"} note="carteira consolidada"/><Metric label="ROAS plataforma" value={`${summary.roas.toFixed(2)}x`} note={brl(summary.platformRevenue)}/><Metric label="ROAS negócio" value={summary.businessRevenue?`${summary.trueRoas.toFixed(2)}x`:"—"} note={summary.businessRevenue?brl(summary.businessRevenue):"Conecte CRM/e-commerce"}/></div>
  <section className="command-hero" data-guide="command-hero"><div><span className="ops-eyebrow">HOJE NA OPERAÇÃO</span><h2>{priorities.length?`${priorities.length} ponto(s) pedem atenção.`:"Carteira sob controle."}</h2><p>{authorized.length?`${fresh}/${authorized.length} fontes sincronizadas nas últimas 2 horas. Use os atalhos para aprofundar análise ou execução.`:"Conecte suas fontes para o Trafinexo monitorar campanhas, resultados, tarefas e oportunidades automaticamente."}</p><div className="command-actions"><button className="btn" onClick={()=>onNavigate("Integrações")}>Conectar dados</button><a className="btn ghost" href="/inteligencia">Inteligência</a><a className="btn ghost" href="/inteligencia/lab">Growth OS</a><a className="btn ghost" href="/operacao">Operação 360</a><button className="btn ghost" onClick={()=>onNavigate("Relatórios")}>Relatórios</button><button className="btn ghost" onClick={()=>onNavigate("Testes A/B")}>Teste A/B</button></div></div><div className="attention-score"><small>Prioridades</small><b>{priorities.length}</b><span>{priorities.length?"por impacto":"estável"}</span></div></section>
  <div className="command-grid"><section className="ops-panel priority-panel" data-guide="priority-list"><div className="section-title"><div><h3>Fila de decisão</h3><p>O que exige ação, em ordem de atenção.</p></div><span>{priorities.length} itens</span></div><div className="priority-list">{!priorities.length?<div className="empty-state"><b>Nenhuma urgência detectada</b><p>O monitoramento continua ativo. Novos desvios e oportunidades aparecerão aqui.</p></div>:priorities.map((p,i)=><button key={`${p.kind}-${i}`} className="priority-item" onClick={()=>onNavigate(p.tab)}><span className={`priority-level ${p.level}`}/><div><b>{p.title}</b><p>{p.text}</p></div><span>→</span></button>)}</div></section>
  <section className="ops-panel"><div className="section-title"><div><h3>Saúde da carteira</h3><p>Resultado e operação por cliente.</p></div><button className="link-button" onClick={()=>onNavigate("Clientes")}>Ver carteira</button></div><div className="client-pulse">{!clients.length?<div className="empty-state"><b>Cadastre seu primeiro cliente</b><p>Depois conecte mídia, CRM e analytics para preencher os indicadores.</p></div>:clients.slice(0,8).map(c=>{const cc=campaigns.filter(x=>x.client_id===c.id),sp=cc.reduce((a,x)=>a+Number(x.spend_cents||0),0),rev=cc.reduce((a,x)=>a+Number(x.revenue_cents||0),0),health=Number(c.health_score||0);return <div key={c.id}><span className={`health-orb ${health>=75?"good":health>=45?"warn":"neutral"}`}>{health?Math.round(health):"—"}</span><div><b>{c.company_name}</b><small>{cc.length} campanhas · {brl(sp)}</small></div><strong>{sp?`${(rev/sp).toFixed(2)}x`:"—"}</strong></div>})}</div></section></div>
  <PortfolioCockpit clients={clients} campaigns={campaigns} tasks={tasks}/>
 </div>
}
function Metric({label,value,note}){return <div><small>{label}</small><b>{value}</b><span>{note}</span></div>}
