"use client";
import {useMemo,useState} from "react";
import {rest} from "../lib/infotecApi";

function metricValue(c,key){const spend=Number(c?.spend_cents||0)/100,leads=Number(c?.leads||0),conv=Number(c?.conversions||0),rev=Number(c?.revenue_cents||0)/100,clicks=Number(c?.clicks||0),imp=Number(c?.impressions||0);if(key==="roas")return spend?rev/spend:0;if(key==="cpl")return leads?spend/leads:0;if(key==="cpa")return conv?spend/conv:0;if(key==="ctr")return imp?clicks/imp:0;if(key==="cvr")return clicks?conv/clicks:0;return conv}
function format(v,key){if(["cpl","cpa"].includes(key))return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});if(["ctr","cvr"].includes(key))return `${(Number(v||0)*100).toFixed(2)}%`;if(key==="roas")return `${Number(v||0).toFixed(2)}x`;return Number(v||0).toLocaleString("pt-BR")}
function normalCdf(x){const t=1/(1+.2316419*Math.abs(x));const d=.3989423*Math.exp(-x*x/2);let p=1-d*t*(.3193815+t*(-.3565638+t*(1.781478+t*(-1.821256+t*1.330274))));return x>=0?p:1-p}
function confidence(a,b,key){let n1,x1,n2,x2;if(key==="ctr"){n1=Number(a?.impressions||0);x1=Number(a?.clicks||0);n2=Number(b?.impressions||0);x2=Number(b?.clicks||0)}else if(key==="cvr"){n1=Number(a?.clicks||0);x1=Number(a?.conversions||0);n2=Number(b?.clicks||0);x2=Number(b?.conversions||0)}else return null;if(n1<50||n2<50)return null;const p1=x1/n1,p2=x2/n2,p=(x1+x2)/(n1+n2),se=Math.sqrt(p*(1-p)*(1/n1+1/n2));if(!se)return null;return Math.min(99.9,(2*normalCdf(Math.abs((p1-p2)/se))-1)*100)}

export default function ExperimentsCenter({workspace,clients,campaigns,experiments,onChanged}){
 const[form,setForm]=useState({client_id:"",name:"",hypothesis:"",metric:"cvr",a:"",b:""}),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const filtered=useMemo(()=>form.client_id?campaigns.filter(c=>c.client_id===form.client_id):campaigns,[campaigns,form.client_id]);
 const rows=useMemo(()=>experiments.map(e=>{const aid=e.variant_a?.campaign_id||e.variant_a?.external_id,bid=e.variant_b?.campaign_id||e.variant_b?.external_id;const a=campaigns.find(c=>c.id===aid||c.external_id===aid),b=campaigns.find(c=>c.id===bid||c.external_id===bid);const key=e.primary_metric||"cvr",av=metricValue(a,key),bv=metricValue(b,key),lowerBetter=["cpl","cpa"].includes(key),winner=a&&b?(lowerBetter?(av&&bv?(av<bv?"A":"B"):null):(av>bv?"A":bv>av?"B":null)):e.winner;return{...e,a,b,key,av,bv,winner,confidence:confidence(a,b,key)}}),[experiments,campaigns]);
 async function create(e){e.preventDefault();if(form.a===form.b){setError("Escolha duas campanhas diferentes.");return}setSaving(true);setError("");try{const a=campaigns.find(c=>c.id===form.a),b=campaigns.find(c=>c.id===form.b);await rest("traf_experiments",{method:"POST",prefer:"return=representation",body:{workspace_id:workspace.id,client_id:form.client_id,name:form.name,hypothesis:form.hypothesis,variable_type:"campaign",status:"running",provider:a?.provider===b?.provider?a?.provider:"cross_channel",source:"trafinexo",sync_status:"monitoring",primary_metric:form.metric,variant_a:{campaign_id:a?.id,external_id:a?.external_id,label:a?.name},variant_b:{campaign_id:b?.id,external_id:b?.external_id,label:b?.name},started_at:new Date().toISOString()}});setForm({client_id:"",name:"",hypothesis:"",metric:"cvr",a:"",b:""});await onChanged()}catch(err){setError(err.message)}finally{setSaving(false)}}
 return <div className="ops-stack"><section className="ops-hero compact"><div><span className="ops-eyebrow">EXPERIMENT ENGINE</span><h2>Testes que acompanham a mídia, não uma planilha.</h2><p>Experimentos nativos detectados nas plataformas aparecem automaticamente. Você também pode comparar duas campanhas em execução e o Trafinexo acompanha o resultado conforme as sincronizações chegam.</p></div><div className="ops-health"><b>{rows.filter(r=>r.status==="running").length}</b><span>testes em execução</span></div></section>
 <section className="ops-panel"><div className="section-title"><div><h3>Novo teste monitorado</h3><p>Defina uma hipótese e compare duas campanhas já no ar.</p></div></div>{error&&<div className="ops-message error">⚠ {error}</div>}<form className="experiment-builder" onSubmit={create}><label>Cliente<select required value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value,a:"",b:""})}><option value="">Selecione</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label><label>Nome do teste<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Oferta A vs Oferta B"/></label><label className="wide">Hipótese<input required value={form.hypothesis} onChange={e=>setForm({...form,hypothesis:e.target.value})} placeholder="Se mudarmos a oferta, esperamos elevar a taxa de conversão..."/></label><label>Métrica principal<select value={form.metric} onChange={e=>setForm({...form,metric:e.target.value})}><option value="cvr">Taxa de conversão</option><option value="ctr">CTR</option><option value="cpl">CPL</option><option value="cpa">CPA</option><option value="roas">ROAS</option></select></label><label>Variante A<select required value={form.a} onChange={e=>setForm({...form,a:e.target.value})}><option value="">Campanha A</option>{filtered.map(c=><option key={c.id} value={c.id}>{c.name} · {c.provider}</option>)}</select></label><label>Variante B<select required value={form.b} onChange={e=>setForm({...form,b:e.target.value})}><option value="">Campanha B</option>{filtered.map(c=><option key={c.id} value={c.id}>{c.name} · {c.provider}</option>)}</select></label><button className="btn" disabled={saving}>{saving?"Criando…":"Iniciar monitoramento"}</button></form></section>
 <section className="ops-panel"><div className="section-title"><div><h3>Experimentos monitorados</h3><p>Inclui testes criados no Trafinexo e experimentos encontrados nas plataformas conectadas.</p></div><span>{rows.length} total</span></div><div className="experiment-list">{!rows.length&&<Empty/>}{rows.map(r=><article key={r.id} className="experiment-row"><div className="experiment-main"><div className="row-top"><span className={`status-chip ${r.status}`}>{r.status==="running"?"Em execução":r.status==="completed"?"Concluído":r.status}</span><span className="source-chip">{r.source==="detected"?`Detectado · ${r.provider}`:"Criado no Trafinexo"}</span></div><h4>{r.name}</h4><p>{r.hypothesis}</p></div>{r.a&&r.b?<div className="variant-compare"><div className={r.winner==="A"?"winner":""}><small>A · {r.a.name}</small><b>{format(r.av,r.key)}</b></div><span>vs</span><div className={r.winner==="B"?"winner":""}><small>B · {r.b.name}</small><b>{format(r.bv,r.key)}</b></div></div>:<div className="experiment-native"><b>{r.provider||"Plataforma"}</b><span>{r.result?.google_status||"Sincronizado"}</span></div>}<div className="confidence-box"><small>Confiança</small><b>{r.confidence!=null?`${r.confidence.toFixed(1)}%`:r.confidence_pct?`${Number(r.confidence_pct).toFixed(1)}%`:"Coletando"}</b><span>{r.confidence!=null&&r.confidence>=90?"Sinal forte":r.confidence!=null?"Ainda inconclusivo":"Aguardando volume"}</span></div></article>)}</div></section>
 </div>
}
function Empty(){return <div className="empty-state"><b>Nenhum teste monitorado ainda</b><p>Conecte Google Ads/TikTok ou crie um teste acima. O Trafinexo passa a acompanhar as variantes automaticamente.</p></div>}
