"use client";
import {useEffect,useMemo,useState} from "react";
import {invoke} from "../lib/infotecApi";

const CONNECT_FN="traf-integration-connect";
const SYNC_FN="traf-integration-hub";
const initials={meta_ads:"M",google_ads:"G",google_analytics:"GA",search_console:"SC",tiktok_ads:"TT",linkedin_ads:"in",microsoft_ads:"MS",hubspot:"H",rd_station:"RD",shopify:"S",webhook_crm:"API"};
const labels={authorized:"Conectada",pending:"Pendente",error:"Erro",active:"Ativa",disconnected:"Desconectada"};

export default function IntegrationsCenter({workspace,clients,integrations,onChanged}){
 const[catalog,setCatalog]=useState([]),[clientId,setClientId]=useState(""),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const[tokenModal,setTokenModal]=useState(null),[token,setToken]=useState(""),[account,setAccount]=useState(""),[shopUrl,setShopUrl]=useState("");
 const[accountsModal,setAccountsModal]=useState(null),[manualAccount,setManualAccount]=useState("");
 useEffect(()=>{loadCatalog()},[]);
 async function loadCatalog(){try{const r=await invoke(CONNECT_FN,{action:"catalog"});setCatalog(r.providers||[])}catch(e){setError(e.message)}}
 const byProvider=useMemo(()=>Object.fromEntries(integrations.filter(i=>(i.client_id||"")===(clientId||"")).map(i=>[i.provider,i])),[integrations,clientId]);
 const groups=useMemo(()=>catalog.reduce((a,p)=>{(a[p.category]??=[]).push(p);return a},{}),[catalog]);
 function resetMessages(){setError("");setNotice("")}
 function providerName(id){return catalog.find(p=>p.id===id)?.name||id}
 function openToken(p){resetMessages();setTokenModal({...p,connectionMode:"token"});setToken("");setAccount("");setShopUrl("")}
 function openOauth(p){resetMessages();if(p.requires_shop){setTokenModal({...p,connectionMode:"oauth"});setShopUrl("");return}oauth(p.id)}
 async function oauth(provider,extra={}){setBusy(provider);resetMessages();try{const r=await invoke(CONNECT_FN,{action:"oauth_start",workspace_id:workspace.id,client_id:clientId||null,provider,...extra});window.location.href=r.authorization_url}catch(e){setError(e.message)}finally{setBusy("")}}
 async function startShopOauth(){if(!tokenModal||!shopUrl)return;setTokenModal(null);await oauth(tokenModal.id,{shop_url:shopUrl})}
 async function connectToken(){if(!tokenModal)return;setBusy(tokenModal.id);resetMessages();try{const r=await invoke(CONNECT_FN,{action:"token_connect",workspace_id:workspace.id,client_id:clientId||null,provider:tokenModal.id,token,external_account_id:account||null,shop_url:shopUrl||null});const name=tokenModal.name;setTokenModal(null);setToken("");setAccount("");setShopUrl("");setNotice(r.check?.ok?`${name} conectada e validada com sucesso.`:`${name} conectada. A credencial foi salva e pode exigir configuração adicional da conta.`);await onChanged()}catch(e){setError(e.message)}finally{setBusy("")}}
 async function test(i){setBusy(`test-${i.provider}`);resetMessages();try{const r=await invoke(CONNECT_FN,{action:"test",integration_id:i.id});setNotice(`${providerName(i.provider)} validada${r.identity?` · ${r.identity}`:""}.`);await onChanged()}catch(e){setError(e.message)}finally{setBusy("")}}
 async function disconnect(i){if(!window.confirm(`Desconectar ${providerName(i.provider)} deste escopo?`))return;setBusy(`disconnect-${i.provider}`);resetMessages();try{await invoke(CONNECT_FN,{action:"disconnect",integration_id:i.id});setNotice(`${providerName(i.provider)} desconectada.`);await onChanged()}catch(e){setError(e.message)}finally{setBusy("")}}
 async function sync(i){setBusy(i.provider);resetMessages();try{const r=await invoke(SYNC_FN,{action:"sync",integration_id:i.id,trigger_type:"manual"});if(r.needs_account_selection){setAccountsModal({integration:i,accounts:r.accounts||[]});setNotice((r.accounts||[]).length?"Escolha a conta que será monitorada.":"A plataforma exige o ID da conta. Informe-o para continuar.")}else{setNotice(`${providerName(i.provider)} sincronizada. ${r.records||0} registro(s) atualizados.`);await onChanged()}}catch(e){setError(e.message)}finally{setBusy("")}}
 async function selectAccount(a){if(!accountsModal)return;const id=a?.id||a?.account_id||manualAccount;if(!id){setError("Informe o ID da conta.");return}setBusy(accountsModal.integration.provider);resetMessages();try{await invoke(CONNECT_FN,{action:"select_account",integration_id:accountsModal.integration.id,external_account_id:id});setAccountsModal(null);setManualAccount("");await onChanged();setNotice("Conta selecionada. Clique em Sincronizar para importar os dados.")}catch(e){setError(e.message)}finally{setBusy("")}}
 return <div className="ops-stack">
   <section className="ops-hero compact"><div><span className="ops-eyebrow">DATA HUB</span><h2>Conecte suas plataformas sem sair do Trafinexo.</h2><p>OAuth quando a plataforma permite; Token/API como alternativa segura. As credenciais seguem direto ao backend e ficam armazenadas no cofre, sem reaparecer no navegador.</p></div><div className="ops-health"><b>{integrations.filter(i=>i.status==="authorized").length}</b><span>conexões ativas</span></div></section>
   <div className="filter-bar"><label>Escopo da conexão<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Workspace / todos os clientes</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label><span className="filter-help">Para agências, conecte a fonte no cliente correto. Para Business Manager/MCC, use o workspace e selecione a conta depois.</span></div>
   {error&&<div className="ops-message error">⚠ {error}</div>}{notice&&<div className="ops-message success" onClick={()=>setNotice("")}>✓ {notice}</div>}
   {Object.entries(groups).map(([group,items])=><section key={group} className="provider-section"><div className="section-title"><h3>{group}</h3><span>{items.length} conectores</span></div><div className="provider-grid">{items.map(p=>{const i=byProvider[p.id];const connected=i?.status==="authorized";const oauthReady=!!p.configured;return <article key={p.id} className={`provider-card ${connected?"connected":""}`}><div className="provider-head"><span className={`provider-mark provider-${p.id}`}>{initials[p.id]||"↗"}</span><div><b>{p.name}</b><small>{p.capabilities.slice(0,4).join(" · ")}</small></div><span className={`connection-dot ${connected?"ok":i?.connection_health==="error"?"bad":""}`}/></div><div className="provider-status"><span>{connected?(labels[i.status]||"Conectada"):oauthReady?"OAuth pronto para conectar":p.fallback?"Conexão por Token/API disponível":"Aguardando credenciais do aplicativo"}</span>{i?.external_account_id&&<small>Conta: {i.external_account_id}</small>}{i?.last_sync_at&&<small>Última sync {new Date(i.last_sync_at).toLocaleString("pt-BR")}</small>}</div><div className="provider-actions">{!connected&&<>{oauthReady&&<button className="btn mini" onClick={()=>openOauth(p)} disabled={busy===p.id}>{busy===p.id?"Abrindo…":"Conectar com OAuth"}</button>}{p.fallback&&<button className={`btn mini ${oauthReady?"ghost":""}`} onClick={()=>openToken(p)}>Token / API</button>}</>}{connected&&<><button className="btn mini" onClick={()=>sync(i)} disabled={busy===i.provider}>{busy===i.provider?"Sincronizando…":"Sincronizar"}</button><button className="btn mini ghost" onClick={()=>test(i)} disabled={busy===`test-${i.provider}`}>{busy===`test-${i.provider}`?"Testando…":"Testar conexão"}</button><button className="btn mini ghost" onClick={()=>disconnect(i)} disabled={busy===`disconnect-${i.provider}`}>Desconectar</button></>}</div>{i?.last_error&&<div className="provider-error">{i.last_error}</div>}</article>})}</div></section>)}
   {tokenModal&&<div className="modal-backdrop"><section className="ops-modal"><button className="modal-close" onClick={()=>setTokenModal(null)}>×</button><span className="ops-eyebrow">{tokenModal.connectionMode==="oauth"?"AUTORIZAÇÃO OFICIAL":"CONEXÃO SEGURA"}</span><h3>{tokenModal.name}</h3>{tokenModal.connectionMode==="oauth"?<><p>Informe sua loja para abrir a autorização oficial da plataforma. Nenhuma senha é enviada ao Trafinexo.</p><label>Loja Shopify<input value={shopUrl} onChange={e=>setShopUrl(e.target.value)} placeholder="sualoja.myshopify.com"/></label><div className="modal-actions"><button className="btn ghost" onClick={()=>setTokenModal(null)}>Cancelar</button><button className="btn" onClick={startShopOauth} disabled={!shopUrl}>Continuar para autorização</button></div></>:<><p>Cole o token ou chave emitida pela própria plataforma. O Trafinexo envia a credencial diretamente ao backend, salva no cofre e faz um teste automático quando possível.</p><label>Token / API key<input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off" placeholder="Cole a credencial aqui"/></label><label>{tokenModal.account_hint||"ID da conta"} <small>(opcional quando a plataforma permite descobrir automaticamente)</small><input value={account} onChange={e=>setAccount(e.target.value)} placeholder={tokenModal.account_hint||"ID da conta"}/></label>{tokenModal.id==="shopify"&&<label>URL da loja<input value={shopUrl} onChange={e=>setShopUrl(e.target.value)} placeholder="sualoja.myshopify.com"/></label>}<div className="modal-actions"><button className="btn ghost" onClick={()=>setTokenModal(null)}>Cancelar</button><button className="btn" onClick={connectToken} disabled={!token||busy===tokenModal.id}>Salvar, testar e conectar</button></div></>}</section></div>}
   {accountsModal&&<div className="modal-backdrop"><section className="ops-modal"><button className="modal-close" onClick={()=>setAccountsModal(null)}>×</button><span className="ops-eyebrow">SELECIONE A CONTA</span><h3>Qual conta deve ser monitorada?</h3>{accountsModal.accounts.length>0?<><p>Encontramos contas autorizadas. Escolha uma agora; as demais podem ser conectadas depois.</p><div className="account-list">{accountsModal.accounts.map(a=><button key={a.id||a.account_id} onClick={()=>selectAccount(a)}><b>{a.name||a.account_name||a.id}</b><small>{a.id||a.account_id}</small></button>)}</div></>:<><p>A autorização foi aceita, mas esta plataforma não retornou automaticamente a conta. Informe o ID mostrado no gerenciador de anúncios.</p><label>ID da conta<input value={manualAccount} onChange={e=>setManualAccount(e.target.value)} placeholder="ID da conta / advertiser"/></label><div className="modal-actions"><button className="btn ghost" onClick={()=>setAccountsModal(null)}>Cancelar</button><button className="btn" onClick={()=>selectAccount(null)} disabled={!manualAccount}>Salvar conta</button></div></>}</section></div>}
 </div>
}
