"use client";
import {useEffect,useMemo,useState} from "react";
import {invoke} from "../lib/infotecApi";

const initials={meta_ads:"M",google_ads:"G",google_analytics:"GA",search_console:"SC",tiktok_ads:"TT",linkedin_ads:"in",microsoft_ads:"MS",hubspot:"H",rd_station:"RD",shopify:"S",webhook_crm:"API"};
const labels={authorized:"Conectada",pending:"Pendente",error:"Erro",active:"Ativa"};

export default function IntegrationsCenter({workspace,clients,integrations,onChanged}){
 const[catalog,setCatalog]=useState([]),[clientId,setClientId]=useState(""),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const[tokenModal,setTokenModal]=useState(null),[token,setToken]=useState(""),[account,setAccount]=useState(""),[shopUrl,setShopUrl]=useState("");
 const[accountsModal,setAccountsModal]=useState(null);
 useEffect(()=>{(async()=>{try{const r=await invoke("traf-integration-hub",{action:"catalog"});setCatalog(r.providers||[])}catch(e){setError(e.message)}})()},[]);
 const byProvider=useMemo(()=>Object.fromEntries(integrations.filter(i=>(i.client_id||"")===(clientId||"")).map(i=>[i.provider,i])),[integrations,clientId]);
 const groups=useMemo(()=>catalog.reduce((a,p)=>{(a[p.category]??=[]).push(p);return a},{}),[catalog]);
 async function oauth(provider){setBusy(provider);setError("");setNotice("");try{const r=await invoke("traf-integration-hub",{action:"oauth_start",workspace_id:workspace.id,client_id:clientId||null,provider});window.location.href=r.authorization_url}catch(e){setError(e.message)}finally{setBusy("")}}
 async function connectToken(){if(!tokenModal)return;setBusy(tokenModal.id);setError("");try{await invoke("traf-integration-hub",{action:"token_connect",workspace_id:workspace.id,client_id:clientId||null,provider:tokenModal.id,token,external_account_id:account||null,shop_url:shopUrl||null});setTokenModal(null);setToken("");setAccount("");setShopUrl("");setNotice(`${tokenModal.name} conectada com credencial protegida.`);await onChanged()}catch(e){setError(e.message)}finally{setBusy("")}}
 async function sync(i){setBusy(i.provider);setError("");setNotice("");try{const r=await invoke("traf-integration-hub",{action:"sync",integration_id:i.id,trigger_type:"manual"});if(r.needs_account_selection){setAccountsModal({integration:i,accounts:r.accounts||[]});setNotice("Escolha a conta de anúncios que será monitorada.")}else{setNotice(`${providerName(i.provider)} sincronizada. ${r.records||0} registro(s) atualizados.`);await onChanged()}}catch(e){setError(e.message)}finally{setBusy("")}}
 async function selectAccount(a){if(!accountsModal)return;setBusy(accountsModal.integration.provider);try{await invoke("traf-integration-hub",{action:"select_account",integration_id:accountsModal.integration.id,external_account_id:a.id||a.account_id});setAccountsModal(null);await onChanged();setNotice("Conta selecionada. Clique em Sincronizar para importar os dados.")}catch(e){setError(e.message)}finally{setBusy("")}}
 function providerName(id){return catalog.find(p=>p.id===id)?.name||id}
 return <div className="ops-stack">
   <section className="ops-hero compact"><div><span className="ops-eyebrow">DATA HUB</span><h2>Conecte as fontes. O Trafinexo faz o resto.</h2><p>Autorize suas contas uma vez para importar campanhas, resultados e testes automaticamente. Tokens manuais ficam criptografados no Vault e nunca aparecem no navegador depois do envio.</p></div><div className="ops-health"><b>{integrations.filter(i=>i.status==="authorized").length}</b><span>conexões ativas</span></div></section>
   <div className="filter-bar"><label>Escopo da conexão<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Workspace / todos os clientes</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label><span className="filter-help">Para agências, conecte a conta no cliente correto. Para uma MCC/Business Manager, use o workspace.</span></div>
   {error&&<div className="ops-message error">⚠ {error}</div>}{notice&&<div className="ops-message success">✓ {notice}</div>}
   {Object.entries(groups).map(([group,items])=><section key={group} className="provider-section"><div className="section-title"><h3>{group}</h3><span>{items.length} conectores</span></div><div className="provider-grid">{items.map(p=>{const i=byProvider[p.id];const connected=i?.status==="authorized";return <article key={p.id} className={`provider-card ${connected?"connected":""}`}><div className="provider-head"><span className={`provider-mark provider-${p.id}`}>{initials[p.id]||"↗"}</span><div><b>{p.name}</b><small>{p.capabilities.slice(0,4).join(" · ")}</small></div><span className={`connection-dot ${connected?"ok":i?.connection_health==="error"?"bad":""}`}/></div><div className="provider-status"><span>{connected?(labels[i.status]||"Conectada"):p.configured?"Pronta para OAuth":p.fallback?"OAuth ou token/API":"OAuth da fábrica"}</span>{i?.last_sync_at&&<small>Última sync {new Date(i.last_sync_at).toLocaleString("pt-BR")}</small>}</div><div className="provider-actions">{!connected&&<><button className="btn mini" onClick={()=>oauth(p.id)} disabled={busy===p.id}>{busy===p.id?"Abrindo…":"Conectar conta"}</button>{p.fallback&&<button className="btn mini ghost" onClick={()=>setTokenModal(p)}>Token / API</button>}</>}{connected&&<><button className="btn mini" onClick={()=>sync(i)} disabled={busy===p.id}>{busy===p.id?"Sincronizando…":"Sincronizar agora"}</button><span className={`health-pill ${i.connection_health||"unknown"}`}>{i.connection_health==="ok"?"Saudável":i.connection_health==="error"?"Requer atenção":"Conectada"}</span></>}</div>{i?.last_error&&<div className="provider-error">{i.last_error}</div>}</article>})}</div></section>)}
   {tokenModal&&<div className="modal-backdrop"><section className="ops-modal"><button className="modal-close" onClick={()=>setTokenModal(null)}>×</button><span className="ops-eyebrow">CONEXÃO SEGURA</span><h3>{tokenModal.name}</h3><p>Cole o token ou chave emitida pela própria plataforma. O Trafinexo envia a credencial diretamente ao backend e salva somente no cofre criptografado.</p><label>Token / API key<input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off" placeholder="Cole a credencial aqui"/></label><label>ID da conta / advertiser ID <small>(opcional)</small><input value={account} onChange={e=>setAccount(e.target.value)} placeholder="Ex.: act_123..., 123-456-7890"/></label>{tokenModal.id==="shopify"&&<label>URL da loja<input value={shopUrl} onChange={e=>setShopUrl(e.target.value)} placeholder="sualoja.myshopify.com"/></label>}<div className="modal-actions"><button className="btn ghost" onClick={()=>setTokenModal(null)}>Cancelar</button><button className="btn" onClick={connectToken} disabled={!token||busy===tokenModal.id}>Salvar e conectar</button></div></section></div>}
   {accountsModal&&<div className="modal-backdrop"><section className="ops-modal"><button className="modal-close" onClick={()=>setAccountsModal(null)}>×</button><span className="ops-eyebrow">SELECIONE A CONTA</span><h3>Qual conta deve ser monitorada?</h3><p>Encontramos mais de uma conta autorizada. Você poderá conectar as demais depois.</p><div className="account-list">{accountsModal.accounts.map(a=><button key={a.id||a.account_id} onClick={()=>selectAccount(a)}><b>{a.name||a.account_name||a.id}</b><small>{a.id||a.account_id}</small></button>)}</div></section></div>}
 </div>
}
