"use client";
import {useEffect,useMemo,useState} from "react";
import {rest} from "../lib/infotecApi";

const toggleFields=[
 ["show_media_spend","Investimento"],["show_platform_metrics","Campanhas e KPIs"],["show_business_revenue","Receita real"],["show_projects","Projetos"],["show_tasks","Tarefas"],["show_approvals","Aprovações"],["show_reports","Relatórios"],["show_social","Instagram orgânico"],["show_forecasts","Previsões"],["show_meetings","Agenda"],["allow_ticket_create","Abrir chamados"]
];
export default function PortalControls({clients=[],settings=[],onChanged}){
 const[selected,setSelected]=useState("");const[draft,setDraft]=useState(null);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
 const current=useMemo(()=>settings.find(s=>s.client_id===selected)||null,[settings,selected]);
 useEffect(()=>{if(!current){setDraft(null);return}setDraft({...current,branding:{agency_name:"",logo_url:"",primary_color:"#147DFF",...(current.branding||{})}})},[current?.id,current?.updated_at]);
 async function save(){if(!draft)return;setBusy(true);setNotice("");try{const body={};for(const [key] of toggleFields)body[key]=Boolean(draft[key]);body.custom_domain=draft.custom_domain||null;body.branding=draft.branding||{};body.updated_at=new Date().toISOString();await rest(`traf_client_portal_settings?id=eq.${draft.id}`,{method:"PATCH",body});setNotice("Configuração do portal atualizada.");await onChanged?.()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 return <section className="ops-panel"><div className="section-title"><div><h3>Personalização por cliente</h3><p>Escolha o que cada cliente vê e aplique white-label no portal.</p></div></div><div className="stack-form"><label>Cliente<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecione</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label>{selected&&!draft&&<div className="empty-state"><b>Portal ainda não habilitado</b><p>Ative o portal acima para liberar as preferências deste cliente.</p></div>}{draft&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:8}}>{toggleFields.map(([key,label])=><label key={key} className="check-line"><input type="checkbox" checked={Boolean(draft[key])} onChange={e=>setDraft({...draft,[key]:e.target.checked})}/>{label}</label>)}</div><label>Nome da agência / marca<input value={draft.branding?.agency_name||""} onChange={e=>setDraft({...draft,branding:{...(draft.branding||{}),agency_name:e.target.value}})} placeholder="Sua Agência"/></label><label>Logo URL<input value={draft.branding?.logo_url||""} onChange={e=>setDraft({...draft,branding:{...(draft.branding||{}),logo_url:e.target.value}})} placeholder="https://.../logo.png"/></label><label>Cor principal<input value={draft.branding?.primary_color||"#147DFF"} onChange={e=>setDraft({...draft,branding:{...(draft.branding||{}),primary_color:e.target.value}})} placeholder="#147DFF"/></label><label>Domínio white-label<input value={draft.custom_domain||""} onChange={e=>setDraft({...draft,custom_domain:e.target.value})} placeholder="painel.suaagencia.com.br"/></label><button className="btn" type="button" onClick={save} disabled={busy}>{busy?"Salvando…":"Salvar personalização"}</button></>}{notice&&<small>{notice}</small>}</div></section>
}
