"use client";
import {useState} from "react";
import {rest} from "../lib/infotecApi";

export default function ReportsCenter({workspace,clients,schedules,portalSettings,onChanged}){
 const[form,setForm]=useState({client_id:"",name:"Relatório mensal de performance",frequency:"monthly",emails:"",approval:true}),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function create(e){e.preventDefault();setSaving(true);setError("");try{await rest("traf_report_schedules",{method:"POST",prefer:"return=representation",body:{workspace_id:workspace.id,client_id:form.client_id,name:form.name,frequency:form.frequency,recipient_emails:form.emails.split(/[;,]/).map(x=>x.trim()).filter(Boolean),include_ai_summary:true,require_approval:form.approval,white_label:true}});setForm({client_id:"",name:"Relatório mensal de performance",frequency:"monthly",emails:"",approval:true});await onChanged()}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function togglePortal(client){const current=portalSettings.find(p=>p.client_id===client.id);setSaving(true);try{if(current)await rest(`traf_client_portal_settings?id=eq.${current.id}`,{method:"PATCH",body:{enabled:!current.enabled,updated_at:new Date().toISOString()}});else await rest("traf_client_portal_settings",{method:"POST",body:{workspace_id:workspace.id,client_id:client.id,enabled:true}});await onChanged()}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function toggleSchedule(s){setSaving(true);try{await rest(`traf_report_schedules?id=eq.${s.id}`,{method:"PATCH",body:{status:s.status==="active"?"paused":"active",updated_at:new Date().toISOString()}});await onChanged()}catch(e){setError(e.message)}finally{setSaving(false)}}
 const clientName=id=>clients.find(c=>c.id===id)?.company_name||"Cliente";
 return <div className="ops-stack"><section className="ops-hero compact"><div><span className="ops-eyebrow">CLIENT SUCCESS</span><h2>Relatórios que explicam o resultado, não só mostram números.</h2><p>Crie rotinas de envio, revisão antes do cliente receber, resumo por IA e portal com permissões. O mesmo link pode acompanhar o cliente durante toda a operação.</p></div><div className="ops-health"><b>{schedules.filter(s=>s.status==="active").length}</b><span>rotinas ativas</span></div></section>
 {error&&<div className="ops-message error">⚠ {error}</div>}
 <div className="command-grid"><section className="ops-panel"><div className="section-title"><div><h3>Nova rotina de relatório</h3><p>O envio automático será consumido pelo n8n assim que o runtime central estiver ativo.</p></div></div><form className="stack-form" onSubmit={create}><label>Cliente<select required value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value})}><option value="">Selecione</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Frequência<select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="weekly">Semanal</option><option value="biweekly">Quinzenal</option><option value="monthly">Mensal</option><option value="manual">Somente manual</option></select></label><label>Destinatários<input value={form.emails} onChange={e=>setForm({...form,emails:e.target.value})} placeholder="cliente@empresa.com; socio@empresa.com"/></label><label className="check-line"><input type="checkbox" checked={form.approval} onChange={e=>setForm({...form,approval:e.target.checked})}/> Exigir minha aprovação antes do envio</label><button className="btn" disabled={saving}>{saving?"Salvando…":"Criar rotina"}</button></form></section>
 <section className="ops-panel"><div className="section-title"><div><h3>Portal do cliente</h3><p>Controle quais clientes têm acesso a uma visão simplificada e segura.</p></div></div><div className="portal-list">{clients.map(c=>{const p=portalSettings.find(x=>x.client_id===c.id);return <div key={c.id}><div><b>{c.company_name}</b><small>{p?.enabled?"Portal habilitado":"Portal desabilitado"}</small></div><button className={`switch-button ${p?.enabled?"on":""}`} onClick={()=>togglePortal(c)} disabled={saving}><span/></button></div>})}{!clients.length&&<div className="empty-state"><b>Nenhum cliente cadastrado</b><p>Cadastre clientes para liberar portais individuais.</p></div>}</div></section></div>
 <section className="ops-panel"><div className="section-title"><div><h3>Relatórios programados</h3><p>White-label, resumo por IA, metas, mídia, testes, criativos e próximos passos.</p></div><span>{schedules.length} rotinas</span></div><div className="schedule-table">{schedules.map(s=><div key={s.id}><div><b>{s.name}</b><small>{clientName(s.client_id)} · {s.frequency==="weekly"?"Semanal":s.frequency==="biweekly"?"Quinzenal":s.frequency==="monthly"?"Mensal":"Manual"}</small></div><div className="schedule-flags"><span>IA {s.include_ai_summary?"✓":"—"}</span><span>Aprovação {s.require_approval?"✓":"—"}</span><span>White-label {s.white_label?"✓":"—"}</span></div><button className={`status-button ${s.status}`} onClick={()=>toggleSchedule(s)}>{s.status==="active"?"Ativo":"Pausado"}</button></div>)}{!schedules.length&&<div className="empty-state"><b>Nenhum relatório programado</b><p>Crie uma rotina acima para não voltar a montar relatório manualmente todo mês.</p></div>}</div></section>
 </div>
}
