"use client";
import {useEffect,useMemo,useState} from "react";
import {clearSession,currentUser,invoke,rest} from "../../../lib/infotecApi";
import {InfotecFooter} from "../../../components/InfotecFooter";
import "../../dashboard/pro.css";
import "../intelligence.css";
import "./growth-os.css";

const groups=["Intelligence","Prediction","Recommendation","Controlled Autonomy"];
const statusLabel={active:"Operante",ready:"Pronto para dados",beta:"Beta"};
export default function GrowthOSLab(){
 const[loading,setLoading]=useState(true),[running,setRunning]=useState(false),[error,setError]=useState(""),[workspace,setWorkspace]=useState(null),[data,setData]=useState(null),[filter,setFilter]=useState("Todos"),[proposals,setProposals]=useState([]);
 async function boot(persist=false){setLoading(true);setError("");try{const u=await currentUser();if(!u){location.href="/login";return}const m=await rest("traf_workspace_members?select=workspace_id,role&limit=1");if(!m?.length)throw Error("Workspace não encontrado");const wid=m[0].workspace_id;setWorkspace({id:wid});const d=await invoke("traf-growth-os",{action:"overview",workspace_id:wid,persist});setData(d);const p=await rest(`traf_autonomy_proposals?workspace_id=eq.${wid}&select=*&order=proposed_at.desc&limit=30`);setProposals(p||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{boot(false)},[]);
 async function refresh(){setRunning(true);try{await boot(true)}finally{setRunning(false)}}
 async function generate(){if(!workspace)return;setRunning(true);setError("");try{await invoke("traf-growth-os",{action:"generate_proposals",workspace_id:workspace.id});const p=await rest(`traf_autonomy_proposals?workspace_id=eq.${workspace.id}&select=*&order=proposed_at.desc&limit=30`);setProposals(p||[])}catch(e){setError(e.message)}finally{setRunning(false)}}
 async function decide(id,decision){if(!workspace)return;setRunning(true);setError("");try{await invoke("traf-growth-os",{action:"proposal_decide",workspace_id:workspace.id,proposal_id:id,decision});const p=await rest(`traf_autonomy_proposals?workspace_id=eq.${workspace.id}&select=*&order=proposed_at.desc&limit=30`);setProposals(p||[])}catch(e){setError(e.message)}finally{setRunning(false)}}
 const modules=useMemo(()=>{const a=data?.modules||[];return filter==="Todos"?a:a.filter(x=>x.group===filter)},[data,filter]);
 if(loading)return <main className="intel-loading"><b>TRAFINEXO</b><span>Montando Growth OS…</span></main>;
 return <main className="intel-page growth-page"><header className="intel-top"><div><span>TRAFINEXO / GROWTH OS</span><h1>Intelligence → Prediction → Recommendation → Autonomy</h1><p>A camada avançada organiza sinais, previsões, recomendações e propostas de execução com guardrails.</p></div><div className="intel-actions"><a href="/inteligencia">← Performance Intelligence</a><button onClick={refresh} disabled={running}>{running?"Atualizando…":"Atualizar e registrar snapshot"}</button><button onClick={()=>{clearSession();location.href="/login"}}>Sair</button></div></header>
 {error&&<div className="intel-error">{error}</div>}
 <section className="growth-summary"><article><small>Módulos</small><b>{data?.summary?.total||0}</b><span>roadmap funcional consolidado</span></article><article><small>Operantes</small><b>{data?.summary?.active||0}</b><span>com dados atuais</span></article><article><small>Prontos</small><b>{data?.summary?.ready||0}</b><span>aguardando fonte/volume</span></article><article><small>Data Quality</small><b>{data?.summary?.data_quality_score||0}/100</b><span>confiança dos sinais</span></article></section>
 <section className="growth-tabs"><button className={filter==="Todos"?"active":""} onClick={()=>setFilter("Todos")}>Todos</button>{groups.map(g=><button key={g} className={filter===g?"active":""} onClick={()=>setFilter(g)}>{g}</button>)}</section>
 <section className="growth-modules">{modules.map(m=><article key={m.id} className={`growth-module ${m.status}`}><div><small>{m.group}</small><span>{statusLabel[m.status]||m.status}</span></div><h2>{m.name}</h2><p>{m.note}</p><footer><b>{m.score}/100</b><em>score de prontidão/qualidade</em></footer></article>)}</section>
 <section className="intel-card autonomy"><div className="card-head"><div><small>CONTROLLED AUTONOMY</small><h2>Fila de propostas aprováveis</h2></div><button onClick={generate} disabled={running}>Gerar propostas agora</button></div><p className="hint">Ações que podem gastar dinheiro ou alterar entrega externa ficam aprovadas e aguardando um conector de escrita homologado. Ações internas seguras podem virar tarefa automaticamente.</p><div className="proposal-list">{!proposals.length?<div className="intel-empty"><b>Nenhuma proposta pendente</b><p>Gere propostas para transformar sinais em próximas ações.</p></div>:proposals.map(p=><div className="proposal" key={p.id}><div><span className={`risk ${p.risk_level}`}>{p.risk_level}</span><b>{p.title}</b><p>{p.rationale}</p><small>{p.status}{p.execution_status?` · ${p.execution_status}`:""}</small></div>{p.status==="proposed"&&<aside><button onClick={()=>decide(p.id,"approve")}>Aprovar</button><button className="ghost" onClick={()=>decide(p.id,"reject")}>Rejeitar</button></aside>}</div>)}</div></section>
 <section className="growth-map"><div className="card-head"><div><small>ARQUITETURA</small><h2>O que foi incorporado ao produto</h2></div></div><div className="growth-map-grid"><article><b>Intelligence</b><p>Competidores, landing pages, jornada, benchmark, atribuição, audience/offer/funnel, social e mercado.</p></article><article><b>Prediction</b><p>Anomalias, sazonalidade, LTV, coortes, geo, placements, saturação, winner prediction, workload, SLA e forecast.</p></article><article><b>Recommendation</b><p>Creative gaps, experiment priority, pacing, reverse planning, cenários, mix, data quality, opportunity, upsell, root cause, playbooks, audits e briefs.</p></article><article><b>Controlled Autonomy</b><p>Fila aprovável, Decision Memory, agentes de experimento/criativo/retenção/growth e Marketing Digital Twin em beta.</p></article></div></section>
 <div className="intel-method"><b>Regra de segurança</b><p>O TrafiNexo pode analisar, prever, recomendar e preparar uma execução. Mudanças em orçamento, campanha ou publicação externa exigem aprovação humana e conector de escrita homologado. O sistema não marca como executado o que a API externa não confirmou.</p></div>
 <InfotecFooter/></main>
}
