"use client";
import {useEffect,useState} from "react";
import {SUPABASE_KEY,SUPABASE_URL} from "../../lib/infotecApi";

async function rpc(name,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||"Não foi possível concluir");return d}
export default function Aprovar(){
 const[data,setData]=useState(null),[error,setError]=useState(""),[done,setDone]=useState(""),[form,setForm]=useState({name:"",email:"",feedback:""});
 const token=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("token"):"";
 useEffect(()=>{if(token)rpc("traf_public_approval_get",{p_token:token}).then(d=>{if(!d)throw new Error("Link inválido ou expirado");setData(d)}).catch(e=>setError(e.message));else setError("Token de aprovação ausente")},[token]);
 async function decide(decision){try{await rpc("traf_public_approval_decide",{p_token:token,p_decision:decision,p_name:form.name||null,p_email:form.email||null,p_feedback:form.feedback||null});setDone(decision);setData({...data,status:decision})}catch(e){setError(e.message)}}
 return <main style={{minHeight:"100vh",background:"#f4f8fc",padding:"32px 16px",color:"#0a1b30"}}><section style={{maxWidth:820,margin:"0 auto",background:"white",border:"1px solid #dce6f0",borderRadius:20,padding:28}}><div style={{fontWeight:900,letterSpacing:1,color:"#147dff"}}>TRAFINEXO <small style={{color:"#66758a"}}>by INFOTEC</small></div>{error?<div style={{marginTop:24,padding:16,borderRadius:12,background:"#fff2f2"}}>⚠ {error}</div>:!data?<p>Carregando material…</p>:<><div style={{marginTop:28}}><small style={{fontWeight:800,color:"#66758a"}}>{data.client} · {data.entity_type} · versão {data.version}</small><h1 style={{margin:"6px 0 10px"}}>{data.title}</h1><p>Status atual: <b>{data.status}</b></p></div>{data.preview_url&&<div style={{margin:"22px 0"}}><a href={data.preview_url} target="_blank" style={{display:"inline-block",padding:"12px 16px",borderRadius:10,background:"#071a33",color:"white",textDecoration:"none"}}>Abrir material para revisão ↗</a></div>}{done?<div style={{padding:18,borderRadius:12,background:"#eef8f1"}}>{done==="approved"?"✓ Material aprovado com sucesso.":"✓ Solicitação de alterações registrada."}</div>:<div style={{display:"grid",gap:12,marginTop:18}}><input placeholder="Seu nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} style={{padding:12,border:"1px solid #dce6f0",borderRadius:10}}/><input placeholder="Seu e-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} style={{padding:12,border:"1px solid #dce6f0",borderRadius:10}}/><textarea rows="4" placeholder="Comentário ou ajustes necessários" value={form.feedback} onChange={e=>setForm({...form,feedback:e.target.value})} style={{padding:12,border:"1px solid #dce6f0",borderRadius:10}}/><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button onClick={()=>decide("approved")} style={{border:0,borderRadius:10,padding:"12px 18px",background:"#147dff",color:"white",fontWeight:800}}>Aprovar material</button><button onClick={()=>decide("changes_requested")} style={{border:"1px solid #dce6f0",borderRadius:10,padding:"12px 18px",background:"white",fontWeight:800}}>Solicitar alterações</button></div></div>}</>}</section></main>
}
