"use client";
import {useEffect,useMemo,useState} from "react";
import {SUPABASE_KEY,SUPABASE_URL} from "../../lib/infotecApi";
import "./portal.css";

async function rpc(name,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||"Não foi possível acessar o portal");return d}
const brl=v=>(Number(v||0)/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const fmt=v=>v?new Date(v).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—";

export default function ClientePortal(){
 const[data,setData]=useState(null),[error,setError]=useState(""),[tab,setTab]=useState("Visão geral"),[ticket,setTicket]=useState({subject:"",description:"",name:"",email:"",priority:"medium"}),[notice,setNotice]=useState("");
 const token=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("token"):"";
 async function load(){if(!token){setError("Link de portal inválido");return}try{const d=await rpc("traf_public_portal_get",{p_token:token});if(!d)throw new Error("Portal indisponível");setData(d)}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[token]);
 const summary=useMemo(()=>{const c=data?.campaigns||[];const spend=c.reduce((a,x)=>a+Number(x.spend_cents||0),0),leads=c.reduce((a,x)=>a+Number(x.leads||0),0),conversions=c.reduce((a,x)=>a+Number(x.conversions||0),0),revenue=c.reduce((a,x)=>a+Number(x.revenue_cents||0),0);return{spend,leads,conversions,revenue,roas:spend?revenue/spend:0,cpl:leads?spend/leads:0}},[data]);
 async function sendTicket(e){e.preventDefault();try{await rpc("traf_public_ticket_create",{p_token:token,p_subject:ticket.subject,p_description:ticket.description,p_name:ticket.name||null,p_email:ticket.email||null,p_priority:ticket.priority});setNotice("Chamado enviado. A equipe já consegue acompanhar pelo portal.");setTicket({...ticket,subject:"",description:""});await load()}catch(e){setError(e.message)}}
 if(error)return <main className="client-error"><h2>Portal de performance</h2><p>{error}</p></main>;
 if(!data)return <main className="client-error">Carregando portal…</main>;
 const settings=data.settings||{},branding=settings.branding||{},accent=branding.primary_color||"#147DFF",portalName=branding.agency_name||"TRAFINEXO";
 const tabs=["Visão geral",...(settings.show_platform_metrics?["Campanhas"]:[]),...(settings.show_projects?["Projetos"]:[]),...(settings.show_forecasts?["Previsões"]:[]),...(settings.show_social?["Social"]:[]),...(settings.show_meetings?["Agenda"]:[]),...(settings.show_tasks?["Tarefas"]:[]),...(settings.show_approvals?["Aprovações"]:[]),...(settings.show_reports?["Relatórios"]:[]),"Chamados"];
 const latestSocial=(data.social||[])[0];
 return <main className="client-portal" style={{"--portal-accent":accent}}><header className="client-portal-header"><div><div className="client-brand">{branding.logo_url&&<img src={branding.logo_url} alt={portalName}/>}<div><b>{portalName}</b><small>Portal de performance</small></div></div><div className="client-account"><b>{data.client.company_name}</b><small>{data.client.segment||"Cliente"}</small></div></div></header><div className="client-portal-main"><div className="client-portal-actions"><nav className="client-tabs">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?"active":""}>{t}</button>)}</nav><button className="client-print" onClick={()=>window.print()}>Baixar / imprimir PDF</button></div>{notice&&<div className="client-notice">{notice}</div>}
 {tab==="Visão geral"&&<><section className="client-hero"><div><small>SAÚDE DA OPERAÇÃO</small><h1>{data.client.company_name}</h1><p>Mídia, projeções, entregas e próximos passos em um único painel ao vivo.</p></div><div className="client-health"><b>{data.client.health_score?Math.round(Number(data.client.health_score)):"—"}</b><span>score de saúde</span></div></section><div className="client-kpis"><Kpi label="Investimento" value={settings.show_media_spend?brl(summary.spend):"Oculto"}/><Kpi label="Leads" value={summary.leads.toLocaleString("pt-BR")}/><Kpi label="Conversões" value={summary.conversions.toLocaleString("pt-BR")}/><Kpi label="ROAS" value={`${summary.roas.toFixed(2)}x`}/><Kpi label="CPL" value={summary.leads?brl(summary.cpl):"—"}/>{latestSocial&&<Kpi label="Seguidores" value={Number(latestSocial.followers||0).toLocaleString("pt-BR")}/>}</div><div className="client-grid"><section className="client-panel"><h3>Campanhas que pedem atenção</h3><p>Status atual das campanhas visíveis.</p><div className="client-list">{(data.campaigns||[]).filter(c=>c.status!=="active").slice(0,5).map((c,i)=><article key={i}><b>{c.name}</b><span>{c.provider} · {c.status}</span></article>)}{!(data.campaigns||[]).some(c=>c.status!=="active")&&<div className="portal-empty">Nenhuma campanha fora do estado ativo.</div>}</div></section><section className="client-panel"><h3>Próximos compromissos</h3><p>Reuniões e checkpoints programados.</p>{(data.meetings||[]).length?(data.meetings||[]).slice(0,5).map((m,i)=><div className="meeting-row" key={i}><div><b>{m.title}</b><small>{fmt(m.starts_at)}</small></div>{m.meeting_url?<a href={m.meeting_url} target="_blank">Entrar ↗</a>:<strong>{m.location||m.status}</strong>}</div>):<div className="portal-empty">Nenhuma reunião próxima.</div>}</section></div></>}
 {tab==="Campanhas"&&<section className="client-list">{(data.campaigns||[]).length?(data.campaigns||[]).map((c,i)=><article className="campaign-card" key={i}><div className="campaign-head"><div><b>{c.name}</b><small>{c.provider}</small></div><span className={`campaign-status ${c.status}`}>{c.status}</span></div><div className="campaign-metrics"><span>Investido<b>{settings.show_media_spend?brl(c.spend_cents):"Oculto"}</b></span><span>Leads<b>{Number(c.leads||0).toLocaleString("pt-BR")}</b></span><span>Conversões<b>{Number(c.conversions||0).toLocaleString("pt-BR")}</b></span><span>ROAS<b>{Number(c.spend_cents)?`${(Number(c.revenue_cents||0)/Number(c.spend_cents)).toFixed(2)}x`:"—"}</b></span></div></article>):<div className="portal-empty">Nenhuma campanha disponível.</div>}</section>}
 {tab==="Projetos"&&<List items={data.projects} render={p=><><b>{p.name}</b><span>{p.status} · {Number(p.progress_pct||0).toFixed(0)}% · {p.ends_on||"sem prazo"}</span></>}/>} 
 {tab==="Tarefas"&&<List items={data.tasks} render={t=><><b>{t.title}</b><span>{t.status} · {t.priority} · {t.due_at?new Date(t.due_at).toLocaleDateString("pt-BR"):"sem prazo"}</span></>}/>} 
 {tab==="Aprovações"&&<List items={data.approvals} render={a=><><b>{a.title}</b><span>{a.status} · versão {a.version}</span>{a.public_token&&<a href={`/aprovar?token=${a.public_token}`}>Revisar material →</a>}</>}/>} 
 {tab==="Relatórios"&&<List items={data.reports} render={r=><><b>{r.period_start||"Período"} → {r.period_end||"atual"}</b><span>{r.status}</span><p>{r.ai_summary}</p>{r.pdf_url&&<a href={r.pdf_url} target="_blank">Abrir relatório ↗</a>}</>}/>} 
 {tab==="Previsões"&&<section className="client-panel"><h3>Projeções</h3><p>Como o período tende a fechar no ritmo atual.</p>{(data.forecasts||[]).length?(data.forecasts||[]).map((f,i)=><div className="forecast-row" key={i}><div><b>{f.metric_key}</b><small>Atual {Number(f.current_value||0).toLocaleString("pt-BR")} · meta {f.target_value==null?"—":Number(f.target_value).toLocaleString("pt-BR")}</small></div><strong>{Number(f.projected_value||0).toLocaleString("pt-BR")}{f.probability_pct!=null?<><br/>{Number(f.probability_pct).toFixed(0)}% confiança</>:null}</strong></div>):<div className="portal-empty">Ainda não há histórico suficiente para previsão.</div>}</section>}
 {tab==="Social"&&<section className="client-grid"><div className="client-panel"><h3>Instagram orgânico</h3><p>Último snapshot disponível.</p>{latestSocial?<div className="social-summary"><span>Seguidores<b>{Number(latestSocial.followers||0).toLocaleString("pt-BR")}</b></span><span>Alcance<b>{Number(latestSocial.reach||0).toLocaleString("pt-BR")}</b></span><span>Engajamentos<b>{Number(latestSocial.engagements||0).toLocaleString("pt-BR")}</b></span></div>:<div className="portal-empty">Instagram ainda não sincronizado.</div>}</div><div className="client-panel"><h3>Histórico</h3><p>Evolução recente dos snapshots.</p>{(data.social||[]).slice(0,12).map((s,i)=><div className="social-row" key={i}><div><b>{new Date(s.snapshot_date+"T12:00:00").toLocaleDateString("pt-BR")}</b><small>{s.provider}</small></div><strong>{Number(s.followers||0).toLocaleString("pt-BR")} seguidores</strong></div>)}</div></section>}
 {tab==="Agenda"&&<section className="client-panel"><h3>Agenda</h3><p>Reuniões de performance e checkpoints.</p>{(data.meetings||[]).length?(data.meetings||[]).map((m,i)=><div className="meeting-row" key={i}><div><b>{m.title}</b><small>{fmt(m.starts_at)} · {m.status}</small></div>{m.meeting_url?<a href={m.meeting_url} target="_blank">Abrir reunião ↗</a>:<strong>{m.location||"Online"}</strong>}</div>):<div className="portal-empty">Nenhuma reunião cadastrada.</div>}</section>}
 {tab==="Chamados"&&<div className="client-grid">{settings.allow_ticket_create!==false&&<section className="client-panel"><h3>Abrir novo chamado</h3><p>Envie uma solicitação diretamente para a equipe.</p><form onSubmit={sendTicket} className="client-form"><input required placeholder="Assunto" value={ticket.subject} onChange={e=>setTicket({...ticket,subject:e.target.value})}/><textarea required rows="5" placeholder="Descreva sua solicitação" value={ticket.description} onChange={e=>setTicket({...ticket,description:e.target.value})}/><input placeholder="Seu nome" value={ticket.name} onChange={e=>setTicket({...ticket,name:e.target.value})}/><input placeholder="Seu e-mail" value={ticket.email} onChange={e=>setTicket({...ticket,email:e.target.value})}/><select value={ticket.priority} onChange={e=>setTicket({...ticket,priority:e.target.value})}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select><button>Enviar chamado</button></form></section>}<section className="client-panel"><h3>Histórico de chamados</h3><p>Acompanhe o andamento das solicitações.</p><List items={data.tickets} render={t=><><b>{t.subject}</b><span>{t.status} · {t.priority} · {new Date(t.created_at).toLocaleDateString("pt-BR")}</span></>}/></section></div>}
 </div></main>
}
function Kpi({label,value}){return <div className="client-kpi"><small>{label}</small><b>{value}</b></div>}
function List({items=[],render}){return <section className="client-list">{items.length?items.map((x,i)=><article key={x.id||i}>{render(x)}</article>):<div className="portal-empty">Nenhum item disponível.</div>}</section>}
