"use client";
import {useEffect,useMemo,useState} from "react";
import {SUPABASE_URL,SUPABASE_KEY,getToken,currentUser,rest} from "../../lib/infotecApi";

const clean=v=>String(v||'').replace(/\D/g,'');
const money=v=>(Number(v||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
async function api(path,{method='GET',body}={}){const r=await fetch(`${SUPABASE_URL}/functions/v1/${path}`,{method,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${getToken()}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d?.error||'request_failed');e.detail=d?.detail||'';throw e}return d}

export default function Assinatura(){
 const[workspace,setWorkspace]=useState(null),[plan,setPlan]=useState(null),[selected,setSelected]=useState('card'),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[paid,setPaid]=useState(false),[pix,setPix]=useState(null),[boleto,setBoleto]=useState(null),[history,setHistory]=useState([]);
 const[name,setName]=useState(''),[doc,setDoc]=useState(''),[phone,setPhone]=useState(''),[postal,setPostal]=useState(''),[address,setAddress]=useState(''),[number,setNumber]=useState(''),[province,setProvince]=useState(''),[city,setCity]=useState(''),[complement,setComplement]=useState('');
 const recent=useMemo(()=>history.filter(h=>h.product_slug==='trafinexo').slice(0,5),[history]);
 async function loadProfile(fallback=''){try{const p=await api('factory-billing-profile');setName(p.legal_name||fallback);setDoc(clean(p.cpf_cnpj));setPhone(clean(p.phone));setPostal(clean(p.postal_code));setAddress(p.address||'');setNumber(p.address_number||'');setProvince(p.province||'');setCity(p.city||'');setComplement(p.address_complement||'');setHistory(Array.isArray(p.history)?p.history:[])}catch{setName(v=>v||fallback)}}
 async function saveProfile(card=false){const d=clean(doc),ph=clean(phone),cep=clean(postal);if(!name.trim()||![11,14].includes(d.length)){setMsg('Informe nome e CPF/CNPJ válidos.');return false}if(card&&(!ph||cep.length!==8||!number.trim())){setMsg('Para cartão, informe telefone, CEP e número.');return false}try{const p=await api('factory-billing-profile',{method:'POST',body:{legal_name:name.trim(),cpf_cnpj:d,phone:ph||undefined,postal_code:cep||undefined,address:address||undefined,address_number:number||undefined,province:province||undefined,city:city||undefined,address_complement:complement||undefined}});setAddress(p.address||address);setProvince(p.province||province);setCity(p.city||city);setPostal(clean(p.postal_code||cep));return true}catch(e){setMsg(`Não foi possível salvar os dados${e.detail?`: ${e.detail}`:'.'}`);return false}}
 async function watch(id){for(let i=0;i<60;i++){try{const d=await api(`factory-asaas-payment-status?session_id=${encodeURIComponent(id)}`);if(d.status==='paid'){setPaid(true);setMsg('');await loadProfile(name);return}if(['cancelled','canceled','expired','refunded'].includes(String(d.status))){setMsg('A cobrança não foi concluída. Tente novamente.');return}}catch{}await new Promise(r=>setTimeout(r,2000))}setMsg('A cobrança continua pendente. O plano será atualizado automaticamente quando o Asaas confirmar.')}
 useEffect(()=>{(async()=>{const u=await currentUser();if(!u){location.href='/login';return}const m=await rest('traf_workspace_members?select=workspace_id,role&limit=1');if(!m?.length||m[0].role!=='owner'){setMsg('Somente o proprietário do workspace pode alterar a assinatura.');return}const w=await rest(`traf_workspaces?id=eq.${m[0].workspace_id}&select=id,name,status,plan_code&limit=1`),ws=w?.[0]||null;setWorkspace(ws);await loadProfile(ws?.name||u.user_metadata?.full_name||'');const r=await fetch(`${SUPABASE_URL}/functions/v1/factory-public-commercial-plans?product=trafinexo`),b=await r.json().catch(()=>({}));setPlan((b?.plans||[]).find(x=>x.code==='trafinexo_complete_monthly')||null);const q=new URLSearchParams(location.search),state=q.get('checkout'),sid=q.get('session');if(state==='cancelled')setMsg('Checkout cancelado.');else if(state==='expired')setMsg('Checkout expirado. Gere uma nova cobrança.');else if(sid)void watch(sid)})()},[]);
 const payload=()=>({plan_code:'trafinexo_complete_monthly',resource_id:workspace?.id,customer:{name:name.trim(),cpfCnpj:clean(doc),phone:clean(phone)||undefined,mobilePhone:clean(phone)||undefined,postalCode:clean(postal)||undefined,address:address||undefined,addressNumber:number||undefined,province:province||undefined,city:city||undefined,addressComplement:complement||undefined}});
 async function pay(){if(!workspace||!plan)return;const card=selected==='card';if(!(await saveProfile(card)))return;setBusy(selected);setPix(null);setBoleto(null);setMsg('Preparando pagamento seguro...');try{if(card){const d=await api('factory-asaas-hosted-checkout-create',{method:'POST',body:payload()});if(!d.checkout_url)throw new Error('checkout_url_missing');location.assign(d.checkout_url);return}if(selected==='pix'){const d=await api('factory-asaas-pix-create',{method:'POST',body:payload()});setPix(d.pix);setMsg('PIX gerado. A liberação é automática após a confirmação.');void watch(d.session_id);return}const d=await api('factory-asaas-boleto-create',{method:'POST',body:payload()});setBoleto({invoice:d.invoice_url,pdf:d.bank_slip_url});setMsg('Boleto gerado. A liberação é automática após a compensação.');void watch(d.session_id)}catch(e){setMsg(`Não foi possível iniciar o pagamento${e.detail?`: ${e.detail}`:'.'}`)}finally{setBusy('')}}
 return <main className="subscription-page"><div className="subscription-shell">
  <a className="subscription-back" href="/dashboard">← Voltar ao painel</a>
  {paid&&<div className="payment-approved"><span>✓</span><div><b>Pagamento aprovado</b><div>Seu TrafiNexo Completo está ativo.</div></div></div>}
  <div className="subscription-layout">
   <aside className="subscription-summary"><small>PLANO ATUAL</small><h1>TrafiNexo Completo</h1><div className="subscription-price">{plan?money(plan.price_cents):'—'} <small>/ mês</small></div><p style={{color:'#cbd9e6',fontSize:12,lineHeight:1.55}}>Uma assinatura para operação, inteligência e relacionamento com seus clientes.</p><div className="subscription-benefits"><span>✓ Clientes e carteira completa</span><span>✓ Meta, Google, TikTok, analytics e CRM</span><span>✓ Alertas, testes, criativos e relatórios</span><span>✓ Portal white-label do cliente</span><span>✓ Inteligência, forecast e Growth OS</span></div></aside>
   <section className="subscription-card">
    <div className="subscription-section"><h2>1. Dados de faturamento</h2><p>Esses dados identificam o responsável pela assinatura.</p><div className="subscription-fields"><input className="subscription-field" value={name} onChange={e=>setName(e.target.value)} placeholder="Nome / razão social"/><input className="subscription-field" value={doc} onChange={e=>setDoc(e.target.value)} placeholder="CPF / CNPJ" inputMode="numeric"/></div></div>
    <div className="subscription-section"><h2>2. Forma de pagamento</h2><p>Escolha como deseja pagar. Dados sensíveis de cartão ficam no ambiente do Asaas.</p><div className="payment-methods">{[['card','Cartão','Renovação automática'],['pix','PIX','QR Code e copia e cola'],['boleto','Boleto','Fatura e PDF']].map(([id,t,s])=><button key={id} className={`payment-method ${selected===id?'active':''}`} onClick={()=>setSelected(id)}><strong>{t}</strong><span>{s}</span></button>)}</div>
    {selected==='card'&&<div className="payment-result"><b>Dados adicionais para cartão</b><p>Informe os dados de cobrança. O cartão e o CVV serão digitados somente no checkout seguro.</p><div className="subscription-fields three"><input className="subscription-field" value={phone} onChange={e=>setPhone(clean(e.target.value))} placeholder="Telefone"/><input className="subscription-field" value={postal} onChange={e=>setPostal(clean(e.target.value).slice(0,8))} onBlur={()=>void saveProfile(false)} placeholder="CEP"/><input className="subscription-field" value={address} onChange={e=>setAddress(e.target.value)} placeholder="Logradouro"/><input className="subscription-field" value={number} onChange={e=>setNumber(e.target.value)} placeholder="Número"/><input className="subscription-field" value={province} onChange={e=>setProvince(e.target.value)} placeholder="Bairro"/><input className="subscription-field" value={city} onChange={e=>setCity(e.target.value)} placeholder="Cidade"/><input className="subscription-field" value={complement} onChange={e=>setComplement(e.target.value)} placeholder="Complemento"/></div></div>}
    <button className="subscription-cta" disabled={!!busy||!plan} onClick={()=>void pay()}>{busy?'Processando...':selected==='card'?'Continuar para checkout seguro':selected==='pix'?'Gerar PIX':'Gerar boleto'}</button>{msg&&<div className="subscription-note">{msg}</div>}
    {pix?.payload&&<div className="payment-result">{pix.image_base64&&<img src={`data:image/png;base64,${pix.image_base64}`} alt="QR Code PIX" style={{width:190,maxWidth:'100%'}}/>}<textarea className="subscription-field" readOnly value={pix.payload}/><button className="btn mini" onClick={()=>navigator.clipboard.writeText(pix.payload||'')}>Copiar PIX</button></div>}
    {boleto&&(boleto.invoice||boleto.pdf)&&<div className="payment-result"><b>Boleto gerado</b><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:8}}>{boleto.invoice&&<a className="btn mini ghost" href={boleto.invoice} target="_blank" rel="noreferrer">Abrir fatura</a>}{boleto.pdf&&<a className="btn mini ghost" href={boleto.pdf} target="_blank" rel="noreferrer">Abrir PDF</a>}</div></div>}</div>
    <div className="subscription-section"><h2>3. Cobranças recentes</h2><div className="payment-history">{recent.length?recent.map(h=><div key={h.id} className="payment-history-row"><span>{String(h.payment_method).includes('card')?'Cartão':h.payment_method==='pix'?'PIX':'Boleto'}</span><strong>{money(h.amount_cents)}</strong><span>{h.status}</span></div>):<p>Nenhuma cobrança registrada ainda.</p>}</div></div>
   </section>
  </div>
 </div></main>
}
