"use client";
import {useEffect,useMemo,useState} from "react";
import {clearSession,currentUser,rest} from "../../lib/infotecApi";

const tabs=["Visão geral","Clientes","Campanhas","Testes A/B","Criativos","Contratos","Metas","Integrações","Sugestões"];
const brl=v=>(Number(v||0)/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const statusLabel=s=>({submitted:"Recebida",ai_review:"IA analisando",planned:"Planejada",developing:"Em desenvolvimento",testing:"Em testes",security_review:"Revisão de segurança",ready_for_approval:"Aguardando aprovação",approved:"Aprovada",deployed:"Publicada",rejected:"Não priorizada",failed:"Falhou"}[s]||s);

export default function Dashboard(){const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[user,setUser]=useState(null);const[workspace,setWorkspace]=useState(null);const[role,setRole]=useState("");const[tab,setTab]=useState("Visão geral");const[clients,setClients]=useState([]);const[campaigns,setCampaigns]=useState([]);const[suggestions,setSuggestions]=useState([]);const[experiments,setExperiments]=useState([]);const[contracts,setContracts]=useState([]);const[integrations,setIntegrations]=useState([]);const[newClient,setNewClient]=useState({company_name:"",segment:"",website:"",instagram:"",monthly_ad_budget_cents:""});const[suggestion,setSuggestion]=useState({title:"",description:"",category:"product"});const[saving,setSaving]=useState(false);

async function load(){setLoading(true);setError("");try{const u=await currentUser();if(!u){window.location.href="/login";return}setUser(u);const m=await rest("traf_workspace_members?select=workspace_id,role&limit=1");if(!m?.length)throw new Error("Workspace não encontrado");setRole(m[0].role);const wid=m[0].workspace_id;const w=await rest(`traf_workspaces?id=eq.${wid}&select=id,name,status,trial_ends_at,plan_code&limit=1`);setWorkspace(w?.[0]||null);const [c,cam,s,exp,con,intg]=await Promise.all([rest(`traf_clients?workspace_id=eq.${wid}&select=*&order=created_at.desc`),rest(`traf_campaigns?workspace_id=eq.${wid}&select=*&order=updated_at.desc`),rest(`traf_suggestions?workspace_id=eq.${wid}&select=*&order=created_at.desc`),rest(`traf_experiments?workspace_id=eq.${wid}&select=*&order=created_at.desc`),rest(`traf_contracts?workspace_id=eq.${wid}&select=*&order=created_at.desc`),rest(`traf_integrations?workspace_id=eq.${wid}&select=*&order=created_at.desc`)]);setClients(c||[]);setCampaigns(cam||[]);setSuggestions(s||[]);setExperiments(exp||[]);setContracts(con||[]);setIntegrations(intg||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
useEffect(()=>{load()},[]);

const summary=useMemo(()=>{const spend=campaigns.reduce((n,x)=>n+Number(x.spend_cents||0),0);const leads=campaigns.reduce((n,x)=>n+Number(x.leads||0),0);const revenue=campaigns.reduce((n,x)=>n+Number(x.revenue_cents||0),0);const active=clients.filter(x=>x.status==="active").length;return{spend,leads,revenue,active,cpl:leads?spend/leads:0,roas:spend?revenue/spend:0}},[clients,campaigns]);
const trialDays=workspace?.trial_ends_at?Math.max(0,Math.ceil((new Date(workspace.trial_ends_at)-Date.now())/86400000)):0;

async function createClient(e){e.preventDefault();if(!workspace)return;setSaving(true);setError("");try{await rest("traf_clients",{method:"POST",prefer:"return=representation",body:{workspace_id:workspace.id,company_name:newClient.company_name,segment:newClient.segment||null,website:newClient.website||null,instagram:newClient.instagram||null,monthly_ad_budget_cents:newClient.monthly_ad_budget_cents?Math.round(Number(newClient.monthly_ad_budget_cents)*100):null,objectives:["Diagnóstico inicial pendente"]}});setNewClient({company_name:"",segment:"",website:"",instagram:"",monthly_ad_budget_cents:""});await load();setTab("Clientes")}catch(e){setError(e.message)}finally{setSaving(false)}}
async function sendSuggestion(e){e.preventDefault();if(!workspace||!user)return;setSaving(true);setError("");try{await rest("traf_suggestions",{method:"POST",prefer:"return=representation",body:{workspace_id:workspace.id,submitted_by:user.id,title:suggestion.title,description:suggestion.description,category:suggestion.category}});setSuggestion({title:"",description:"",category:"product"});await load();setTab("Sugestões")}catch(e){setError(e.message)}finally{setSaving(false)}}
function logout(){clearSession();window.location.href="/login"}

if(loading)return <main className="dash-loading"><div className="auth-brand"><span>T</span><div><strong>TRAFINEXO</strong><small>Carregando sua operação…</small></div></div></main>;
if(!workspace)return <main className="dash-loading"><p>{error||"Não foi possível carregar o workspace."}</p><a href="/login">Voltar ao login</a></main>;

return <main className="dashboard-shell"><aside className="dash-side"><a className="dash-brand" href="/"><span>T</span><div><b>TRAFINEXO</b><small>by INFOTEC</small></div></a><nav>{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</nav><div className="side-bottom"><small>{workspace.status==="trial"?`Teste grátis · ${trialDays} dias restantes`:workspace.status}</small><button onClick={logout}>Sair</button></div></aside>
<section className="dash-main"><header className="dash-top"><div><small>{workspace.name}</small><h1>{tab}</h1></div><div className="dash-user"><span>{(user?.user_metadata?.full_name||user?.email||"U").slice(0,1).toUpperCase()}</span><div><b>{user?.user_metadata?.full_name||"Gestor"}</b><small>{role}</small></div></div></header>{error&&<div className="dash-error">⚠ {error}</div>}

{tab==="Visão geral"&&<><div className="dash-kpis"><Kpi label="Clientes ativos" value={summary.active} note={`${clients.length} na carteira`}/><Kpi label="Investimento monitorado" value={brl(summary.spend)} note="Campanhas sincronizadas"/><Kpi label="CPL médio" value={summary.leads?brl(summary.cpl):"—"} note={`${summary.leads} leads`}/><Kpi label="ROAS médio" value={summary.spend?`${summary.roas.toFixed(2)}x`:"—"} note="Receita atribuída"/></div><div className="dash-grid"><article className="dash-card wide"><CardTitle title="Prioridades da operação" tag="IA preparada"/><div className="priority-list">{clients.length===0?<p>Cadastre o primeiro cliente. O evento de onboarding será enviado para o diagnóstico 360°.</p>:clients.slice(0,4).map(c=><div key={c.id}><span className={`health-dot ${c.status}`}/><div><b>{c.company_name}</b><small>{c.diagnosis&&Object.keys(c.diagnosis).length?"Diagnóstico disponível":"Diagnóstico 360° aguardando processamento"}</small></div><em>{c.health_score?`${Math.round(c.health_score)}/100`:"—"}</em></div>)}</div></article><article className="dash-card"><CardTitle title="Teste gratuito" tag={`${trialDays} dias`}/><p className="big-note">Seu workspace está preparado para clientes, campanhas, testes, contratos e sugestões.</p><div className="progress"><i style={{width:`${Math.max(4,100-(trialDays/15*100))}%`}}/></div><small>Use o piloto para registrar o que precisa ser melhorado.</small></article></div></>}

{tab==="Clientes"&&<div className="dash-grid"><article className="dash-card"><CardTitle title="Novo cliente" tag="Diagnóstico 360°"/><form className="dash-form" onSubmit={createClient}><input required placeholder="Empresa" value={newClient.company_name} onChange={e=>setNewClient({...newClient,company_name:e.target.value})}/><input placeholder="Segmento" value={newClient.segment} onChange={e=>setNewClient({...newClient,segment:e.target.value})}/><input placeholder="Site" value={newClient.website} onChange={e=>setNewClient({...newClient,website:e.target.value})}/><input placeholder="Instagram" value={newClient.instagram} onChange={e=>setNewClient({...newClient,instagram:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="Verba mensal em R$" value={newClient.monthly_ad_budget_cents} onChange={e=>setNewClient({...newClient,monthly_ad_budget_cents:e.target.value})}/><button className="btn" disabled={saving}>{saving?"Salvando…":"Cadastrar e iniciar diagnóstico"}</button></form></article><article className="dash-card wide"><CardTitle title="Carteira" tag={`${clients.length} cliente(s)`}/><div className="data-list">{clients.length?clients.map(c=><div key={c.id}><div><b>{c.company_name}</b><small>{c.segment||"Segmento não informado"} · {c.status}</small></div><span>{c.monthly_ad_budget_cents?brl(c.monthly_ad_budget_cents):"Sem verba definida"}</span></div>):<Empty text="Nenhum cliente cadastrado ainda."/>}</div></article></div>}

{tab==="Campanhas"&&<Module title="Campanhas conectadas" count={campaigns.length} empty="As campanhas aparecerão aqui quando Meta Ads/Google Ads forem conectados." rows={campaigns.map(x=>[x.name,`${x.provider} · ${x.status}`,`${brl(x.spend_cents)} · ${x.leads} leads`])}/>} 
{tab==="Testes A/B"&&<Module title="Experimentos" count={experiments.length} empty="Crie e acompanhe hipóteses, variantes, vencedor e confiança estatística." rows={experiments.map(x=>[x.name,x.hypothesis,x.status])}/>} 
{tab==="Criativos"&&<Module title="Biblioteca de criativos" count={0} empty="Imagens, vídeos, copies, headlines, performance e fadiga ficarão centralizados aqui." rows={[]}/>} 
{tab==="Contratos"&&<Module title="Contratos" count={contracts.length} empty="Cadastre escopo, fee, verba, vencimento e renovação por cliente." rows={contracts.map(x=>[x.title,x.status,brl(x.monthly_fee_cents)])}/>} 
{tab==="Metas"&&<Module title="Metas e projeções" count={0} empty="Metas de leads, vendas, CPL, CPA, ROAS e orçamento serão comparadas com projeções automáticas." rows={[]}/>} 
{tab==="Integrações"&&<div className="dash-card"><CardTitle title="Central de integrações" tag={`${integrations.filter(x=>x.status==="connected").length} conectada(s)`}/><div className="integration-grid">{[["Meta Ads","Facebook + Instagram"],["Google Ads","Pesquisa, Display e YouTube"],["Google Analytics","Funil e conversão"],["TikTok Ads","Próxima fase"],["CRM","Leads e vendas"],["WhatsApp","Alertas e operação"]].map(([a,b])=><div key={a}><span>◉</span><div><b>{a}</b><small>{b}</small></div><em>Preparado</em></div>)}</div><p className="module-note">As credenciais serão conectadas por OAuth/segredos no backend. Nenhum token sensível será salvo no navegador.</p></div>}

{tab==="Sugestões"&&<div className="dash-grid"><article className="dash-card"><CardTitle title="Sugerir melhoria" tag="Pipeline com IA"/><p className="module-note">Descreva uma dor ou ideia. O evento entra na fila da fábrica para análise, especificação, desenvolvimento assistido, testes e segurança.</p><form className="dash-form" onSubmit={sendSuggestion}><input required placeholder="Título da melhoria" value={suggestion.title} onChange={e=>setSuggestion({...suggestion,title:e.target.value})}/><select value={suggestion.category} onChange={e=>setSuggestion({...suggestion,category:e.target.value})}><option value="product">Produto</option><option value="ux">Experiência/UX</option><option value="integration">Integração</option><option value="report">Relatório</option><option value="automation">Automação</option><option value="bug">Correção</option></select><textarea required rows="6" placeholder="Explique o problema, como acontece e o resultado que você espera." value={suggestion.description} onChange={e=>setSuggestion({...suggestion,description:e.target.value})}/><button className="btn" disabled={saving}>{saving?"Enviando…":"Enviar para análise"}</button></form></article><article className="dash-card wide"><CardTitle title="Fila de melhorias" tag={`${suggestions.length} registrada(s)`}/><div className="suggestion-list">{suggestions.length?suggestions.map(s=><div key={s.id}><div><b>{s.title}</b><small>{s.ai_summary||s.description}</small><div className="suggestion-meta"><span>{s.category}</span>{s.ai_priority&&<span>Prioridade {s.ai_priority}</span>}{s.ai_risk&&<span>Risco {s.ai_risk}</span>}</div></div><em>{statusLabel(s.status)}</em></div>):<Empty text="Nenhuma sugestão enviada ainda."/>}</div><div className="pipeline-note"><b>Fluxo:</b> sugestão → IA → especificação → desenvolvimento → testes → segurança → aprovação → produção.</div></article></div>}
</section></main>}

function Kpi({label,value,note}){return <article className="dash-kpi"><small>{label}</small><b>{value}</b><span>{note}</span></article>}
function CardTitle({title,tag}){return <div className="card-title"><h3>{title}</h3><span>{tag}</span></div>}
function Empty({text}){return <div className="empty-state">{text}</div>}
function Module({title,count,empty,rows}){return <article className="dash-card"><CardTitle title={title} tag={`${count} registro(s)`}/>{rows.length?<div className="data-list">{rows.map((r,i)=><div key={i}><div><b>{r[0]}</b><small>{r[1]}</small></div><span>{r[2]}</span></div>)}</div>:<Empty text={empty}/>}</article>}
