"use client";
import {useEffect,useMemo,useState} from "react";
import {clearSession,currentUser,invoke,rest} from "../../lib/infotecApi";
import {InfotecFooter} from "../../components/InfotecFooter";
import "../dashboard/pro.css";
import "./intelligence.css";

const brl=v=>(Number(v||0)/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const pct=v=>`${Number(v||0).toFixed(0)}%`;
const scoreClass=v=>Number(v)>=75?"good":Number(v)>=50?"warn":"bad";

export default function InteligenciaPage(){
 const[loading,setLoading]=useState(true),[running,setRunning]=useState(false),[user,setUser]=useState(null),[workspace,setWorkspace]=useState(null),[analysis,setAnalysis]=useState(null),[error,setError]=useState("");
 const[budget,setBudget]=useState("5000"),[budgetClient,setBudgetClient]=useState(""),[scenario,setScenario]=useState(null),[question,setQuestion]=useState("O que exige minha atenção hoje?"),[copilot,setCopilot]=useState(null);
 async function boot(){setLoading(true);setError("");try{const u=await currentUser();if(!u){location.href="/login";return}setUser(u);const memberships=await rest("traf_workspace_members?select=workspace_id,role&limit=1");if(!memberships?.length)throw new Error("Workspace não encontrado");const wid=memberships[0].workspace_id;const ws=await rest(`traf_workspaces?id=eq.${wid}&select=*&limit=1`);setWorkspace(ws?.[0]||{id:wid});const data=await invoke("traf-performance-intelligence",{action:"analyze",workspace_id:wid});setAnalysis(data)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{boot()},[]);
 async function refreshSnapshots(){if(!workspace)return;setRunning(true);setError("");try{const data=await invoke("traf-performance-intelligence",{action:"snapshot",workspace_id:workspace.id});setAnalysis(data.analysis)}catch(e){setError(e.message)}finally{setRunning(false)}}
 async function simulateBudget(){if(!workspace)return;setRunning(true);setError("");try{const cents=Math.round(Number(String(budget).replace(",","."))*100);const data=await invoke("traf-performance-intelligence",{action:"budget_optimize",workspace_id:workspace.id,client_id:budgetClient||null,budget_cents:cents,persist:true});setScenario(data)}catch(e){setError(e.message)}finally{setRunning(false)}}
 async function ask(){if(!workspace||!question.trim())return;setRunning(true);setError("");try{const data=await invoke("traf-performance-intelligence",{action:"copilot",workspace_id:workspace.id,question});setCopilot(data)}catch(e){setError(e.message)}finally{setRunning(false)}}
 const clients=analysis?.clients||[];const incidents=analysis?.incidents||[];const w=analysis?.workspace||{};
 const highestRisk=useMemo(()=>[...clients].sort((a,b)=>b.churn_risk_pct-a.churn_risk_pct)[0],[clients]);
 const trackingIssues=clients.filter(c=>Number(c.tracking?.failed_checks||0)+Number(c.tracking?.bad_integrations||0)>0);
 if(loading)return <main className="intel-loading"><b>TRAFINEXO</b><span>Preparando inteligência da operação…</span></main>;
 return <main className="intel-page"><header className="intel-top"><div><span>TRAFINEXO / INTELIGÊNCIA</span><h1>Performance Intelligence</h1><p>Descubra onde o dinheiro está sendo perdido, onde vale escalar e qual é a próxima melhor ação.</p></div><div className="intel-actions"><a href="/dashboard">← Central de comando</a><button onClick={refreshSnapshots} disabled={running}>{running?"Analisando…":"Atualizar inteligência"}</button><button onClick={()=>{clearSession();location.href="/login"}}>Sair</button></div></header>
 {error&&<div className="intel-error">{error}</div>}
 <section className="intel-kpis"><Kpi label="Investimento analisado" value={brl(w.spend_cents)} note={`${w.clients||0} clientes`}/><Kpi label="ROAS negócio" value={`${Number(w.business_roas||0).toFixed(2)}x`} note={brl(w.revenue_cents)}/><Kpi label="Profit ROAS" value={`${Number(w.profit_roas||0).toFixed(2)}x`} note="lucro operacional estimado"/><Kpi label="Health médio" value={`${Number(w.avg_health_score||0).toFixed(0)}/100`} note={`${w.high_churn_clients||0} em risco alto`}/><Kpi label="Incidentes críticos" value={String(w.critical_incidents||0)} note={`${incidents.length} sinais totais`}/></section>

 <section className="intel-grid two"><article className="intel-card decision"><div className="card-head"><div><small>DAILY DECISION BRIEF</small><h2>O que exige atenção agora</h2></div><span>{incidents.length} sinais</span></div>{!incidents.length?<Empty title="Nenhum incidente crítico" text="A operação não apresenta desvios críticos nos dados sincronizados."/>:<div className="incident-list">{incidents.slice(0,7).map((i,idx)=><div className={`incident ${i.severity}`} key={`${i.client_id}-${i.type}-${idx}`}><i/><div><b>{i.company_name} · {i.title}</b><p>{i.detail}</p></div><span>{i.severity}</span></div>)}</div>}</article>
 <article className="intel-card"><div className="card-head"><div><small>TRACKING GUARDIAN</small><h2>Saúde da mensuração</h2></div><span className={trackingIssues.length?"pill bad":"pill good"}>{trackingIssues.length?`${trackingIssues.length} atenção`:'Estável'}</span></div>{!clients.length?<Empty title="Sem clientes" text="Conecte clientes e fontes para ativar o Guardian."/>:<div className="health-list">{clients.slice(0,8).map(c=><div key={c.client_id}><span className={`score ${scoreClass(c.tracking_score)}`}>{Math.round(c.tracking_score)}</span><div><b>{c.company_name}</b><small>{c.tracking.failed_checks} check(s) falhos · {c.tracking.bad_integrations} integração(ões) com erro</small></div></div>)}</div>}</article></section>

 <section className="intel-card"><div className="card-head"><div><small>CLIENT HEALTH 360 + CHURN PREDICTOR</small><h2>Carteira por resultado, operação e relacionamento</h2></div>{highestRisk&&<span>Maior risco: {highestRisk.company_name} · {pct(highestRisk.churn_risk_pct)}</span>}</div><div className="client-table"><div className="client-row head"><span>Cliente</span><span>Health</span><span>Churn</span><span>Profit ROAS</span><span>Lead Quality</span><span>Tracking</span><span>Criativo</span></div>{clients.map(c=><div className="client-row" key={c.client_id}><span><b>{c.company_name}</b><small>{c.segment||"Sem segmento"}</small></span><span><em className={`dot ${scoreClass(c.health_score)}`}/>{Math.round(c.health_score)}/100</span><span>{pct(c.churn_risk_pct)}</span><span>{Number(c.profit_roas).toFixed(2)}x</span><span>{Math.round(c.lead_quality_score)}/100</span><span>{Math.round(c.tracking_score)}/100</span><span>{Math.round(c.creative_score)}/100</span></div>)}</div></section>

 <section className="intel-grid two"><article className="intel-card"><div className="card-head"><div><small>LEAD QUALITY</small><h2>Lead barato não basta</h2></div></div><div className="quality-grid">{clients.slice(0,6).map(c=><div key={c.client_id}><b>{c.company_name}</b><strong>{Math.round(c.lead_quality_score)}/100</strong><small>CPL {c.cpl_cents==null?'—':brl(c.cpl_cents)}</small><small>CPL qualificado {c.qualified_cpl_cents==null?'—':brl(c.qualified_cpl_cents)}</small><small>CAC {c.cac_cents==null?'—':brl(c.cac_cents)}</small></div>)}</div></article>
 <article className="intel-card"><div className="card-head"><div><small>CREATIVE INTELLIGENCE</small><h2>Fadiga + DNA de performance</h2></div></div><div className="creative-list">{[...clients].sort((a,b)=>b.creative.avg_fatigue-a.creative.avg_fatigue).slice(0,6).map(c=><div key={c.client_id}><div><b>{c.company_name}</b><small>Hook médio {Number(c.creative.avg_hook||0).toFixed(0)} · Score criativo {Math.round(c.creative_score)}/100</small></div><strong>Fadiga {Number(c.creative.avg_fatigue||0).toFixed(0)}</strong></div>)}</div><p className="hint">Perfis de Creative DNA podem armazenar hook, ângulo, CTA, oferta, formato e tags para aprender padrões vencedores.</p></article></section>

 <section className="intel-grid two"><article className="intel-card optimizer"><div className="card-head"><div><small>BUDGET OPTIMIZER</small><h2>Simule a melhor distribuição de verba</h2></div><span>Sem alteração automática</span></div><div className="form-row"><label>Orçamento (R$)<input value={budget} onChange={e=>setBudget(e.target.value)} inputMode="decimal"/></label><label>Cliente<select value={budgetClient} onChange={e=>setBudgetClient(e.target.value)}><option value="">Carteira inteira</option>{clients.map(c=><option value={c.client_id} key={c.client_id}>{c.company_name}</option>)}</select></label><button onClick={simulateBudget} disabled={running}>Simular e salvar cenário</button></div>{scenario&&<div className="scenario"><div className="scenario-summary"><span><small>Verba</small><b>{brl(scenario.budget_cents)}</b></span><span><small>Leads projetados</small><b>{Number(scenario.projected_leads||0).toFixed(0)}</b></span><span><small>Receita projetada</small><b>{brl(scenario.projected_revenue_cents)}</b></span><span><small>Risco</small><b>{Math.round(scenario.risk_score||0)}/100</b></span></div><div className="allocation-list">{scenario.allocations?.slice(0,8).map(a=><div key={`${a.provider}-${a.external_id}`}><span><b>{a.name}</b><small>{a.provider} · ROAS observado {a.observed_roas}x</small></span><strong>{brl(a.recommended_budget_cents)}</strong></div>)}</div><p className="guardrail">Qualquer execução em plataforma de anúncios continua exigindo aprovação humana.</p></div>}</article>
 <article className="intel-card"><div className="card-head"><div><small>FORECAST</small><h2>Probabilidade de bater metas</h2></div><span>30 dias</span></div><div className="forecast-list">{clients.slice(0,7).map(c=><div key={c.client_id}><div><b>{c.company_name}</b><small>Projeção: {Number(c.forecast.projected_leads||0).toFixed(0)} leads · {brl(c.forecast.projected_revenue_cents)}</small></div><span>{c.forecast.lead_target_probability_pct==null?'Sem meta':`${pct(c.forecast.lead_target_probability_pct)} da meta`}</span></div>)}</div><p className="hint">A previsão atual é uma linha de base explicável; ganha precisão conforme histórico diário e CRM aumentam.</p></article></section>

 <section className="intel-card copilot"><div className="card-head"><div><small>TRAFINEXO COPILOT</small><h2>Pergunte à sua operação</h2></div><span>Analítico e explicável</span></div><div className="copilot-form"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')ask()}} placeholder="Ex.: qual cliente está em risco?"/><button onClick={ask} disabled={running}>Perguntar</button></div><div className="quick-questions">{["Qual cliente está em risco?","Onde devo colocar verba?","Tem falha de tracking?","Como está o Profit ROAS?","Qual a qualidade dos leads?","Há fadiga criativa?"].map(q=><button key={q} onClick={()=>{setQuestion(q)}}>{q}</button>)}</div>{copilot&&<div className="copilot-answer"><b>Resposta</b><p>{copilot.answer}</p><small>Modo: inteligência analítica explicável. Evidências permanecem disponíveis para auditoria.</small></div>}</section>
 <div className="intel-method"><b>Metodologia transparente</b><p>{analysis?.methodology||"Os indicadores usam os dados disponíveis na operação."} Profit ROAS é uma estimativa operacional e não substitui DRE quando custo do produto não estiver integrado.</p></div>
 <InfotecFooter/>
 </main>
}
function Kpi({label,value,note}){return <article><small>{label}</small><b>{value}</b><span>{note}</span></article>}
function Empty({title,text}){return <div className="intel-empty"><b>{title}</b><p>{text}</p></div>}
